In [47]:
import Pkg
Pkg.add("ScenTrees")
Pkg.add("FinanceModels")
Pkg.add("EconomicScenarioGenerators")
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("CSV")
Pkg.add("DataFrames")


   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No 

In [97]:
using  CSV, DataFrames, LinearAlgebra, ScenTrees, Distributions

In [49]:
inflation_source = CSV.read("../sb_gbi/inflation_scenarios.csv",DataFrame)
equity_source = CSV.read("../sb_gbi/equity_scenarios.csv",DataFrame)
println(describe(inflation_source))
println(describe(equity_source))

51×7 DataFrame
 Row │ variable    mean       min      median    max       nmissing  eltype   
     │ Symbol      Float64    Float64  Float64   Float64   Int64     DataType 
─────┼────────────────────────────────────────────────────────────────────────
   1 │ 0.040300    0.0403      0.0403  0.0403    0.0403           0  Float64
   2 │ 0.014355    0.0404836   0.0123  0.038629  0.161131         0  Float64
   3 │ 0.090209    0.0405224   0.0123  0.03794   0.168142         0  Float64
   4 │ 0.047505    0.0403158   0.0123  0.03751   0.158611         0  Float64
   5 │ 0.012300    0.0402553   0.0123  0.037425  0.165503         0  Float64
   6 │ 0.012300_1  0.0402959   0.0123  0.037519  0.164738         0  Float64
   7 │ 0.033621    0.0402064   0.0123  0.037467  0.162832         0  Float64
   8 │ 0.014701    0.0402702   0.0123  0.037353  0.152392         0  Float64
   9 │ 0.042845    0.0402596   0.0123  0.037286  0.175204         0  Float64
  10 │ 0.045539    0.0402009   0.0123  0.037396  0.1614

In [50]:
inflation = Matrix(inflation_source[1:5,1:6])
equity = Matrix(equity_source[1:5,1:6])

returns = cat(inflation,equity,dims=3)
returns = permutedims(returns,(2,3,1))

6×2×5 Array{Float64, 3}:
[:, :, 1] =
 0.0403     0.183608
 0.035158   0.040727
 0.031416   0.130638
 0.046096   0.167958
 0.018379  -0.178384
 0.043002   0.032183

[:, :, 2] =
 0.0403     0.057796
 0.013222  -0.015669
 0.0123     0.01473
 0.043899   0.15795
 0.027086  -0.133039
 0.050294  -0.024649

[:, :, 3] =
 0.0403    -0.042034
 0.039912   0.071062
 0.040263   0.211914
 0.035394   0.19843
 0.0123     0.246116
 0.0123     0.020742

[:, :, 4] =
 0.0403     0.048233
 0.016048   0.002585
 0.0123     0.069304
 0.0123    -0.053078
 0.03366   -0.156461
 0.0123     0.279966

[:, :, 5] =
 0.0403    -0.097277
 0.065174   0.278737
 0.052422   0.249458
 0.071214   0.093802
 0.05068    0.071716
 0.035161   0.007833

In [51]:
inflation = Matrix(inflation_source[:,1:50])
equity = Matrix(equity_source)

r_long = cat(inflation,equity,dims=3)
r_long = permutedims(r_long,(2,3,1)) 

50×2×99999 Array{Float64, 3}:
[:, :, 1] =
 0.0403     0.183608
 0.035158   0.040727
 0.031416   0.130638
 0.046096   0.167958
 0.018379  -0.178384
 0.043002   0.032183
 0.029849   0.122386
 0.043892  -0.049013
 0.033638  -0.230813
 0.027528  -0.230181
 ⋮         
 0.028233   0.204203
 0.027208   0.084194
 0.040718  -0.195554
 0.026403   0.164883
 0.0688     0.105274
 0.013082   0.357969
 0.019406   0.310636
 0.06628    0.259417
 0.09403    0.106576

[:, :, 2] =
 0.0403     0.057796
 0.013222  -0.015669
 0.0123     0.01473
 0.043899   0.15795
 0.027086  -0.133039
 0.050294  -0.024649
 0.071821  -0.002556
 0.091165   0.101583
 0.055169   0.042812
 0.0123     0.170594
 ⋮         
 0.076536   0.108522
 0.068139   0.101433
 0.026111   0.089037
 0.054689  -0.170575
 0.036394   0.116987
 0.020704   0.206452
 0.0123     0.181475
 0.019199   0.038817
 0.021789   0.09112

[:, :, 3] =
 0.0403    -0.042034
 0.039912   0.071062
 0.040263   0.211914
 0.035394   0.19843
 0.0123     0.246116
 0.0123  

In [52]:
size(r_long)

(50, 2, 99999)

In [53]:
using Base.Iterators

function take_returns_in_periods(r,timestamps)
    end_index = cumsum(timestamps)
    start_index = end_index - timestamps .+ 1
    n_scenarios = size(r,3)
    n_assets = size(r,2)
    t = length(timestamps)
    result = zeros(t,n_assets,n_scenarios)
    for (index, dt) in enumerate(timestamps)
        result[index,:,:] = sum(log1p.(r[start_index[index]:end_index[index],:,:]),dims=1)
    end    
    return result
    
end

t_returns = take_returns_in_periods(r_long,[1,1,1,1])
t_returns = t_returns .+ 1
t_returns = cumprod(t_returns,dims=1)

4×2×99999 Array{Float64, 3}:
[:, :, 1] =
 1.03951  1.16857
 1.07543  1.21522
 1.10869  1.36442
 1.15866  1.57626

[:, :, 2] =
 1.03951  1.05619
 1.05316  1.03951
 1.06604  1.05471
 1.11184  1.20938

[:, :, 3] =
 1.03951  0.957057
 1.08019  1.02276
 1.12283  1.21933
 1.16188  1.44005

;;; … 

[:, :, 99997] =
 1.03951  1.11254
 1.10471  1.21429
 1.16755  0.79461
 1.2092   0.81823

[:, :, 99998] =
 1.03951  0.843088
 1.06731  0.42154
 1.12895  0.446199
 1.18571  0.520427

[:, :, 99999] =
 1.03951  0.974346
 1.05222  0.988072
 1.08077  1.14682
 1.09398  1.23136

In [77]:
take_returns_in_periods(transpose(equity),[1,1,1,1,1,1,1,1,1,1,1])

11×99999×1 Array{Float64, 3}:
[:, :, 1] =
  0.168567    0.0561875   -0.042943   …   0.112538   -0.156912   -0.0256543
  0.0399195  -0.0157931    0.0686507      0.0914591  -0.500004    0.0140873
  0.122782    0.0146226    0.192201      -0.345618    0.0584981   0.160669
  0.155257    0.146651     0.181012       0.0297258   0.166355    0.0737104
 -0.196482   -0.142761     0.220032       0.112097   -0.182008    0.162717
  0.031676   -0.0249579    0.0205298  …   0.137385    0.180321    0.0541633
  0.115457   -0.00255927   0.200512      -0.0785487   0.243794    0.0748041
 -0.0502549   0.0967482    0.102326      -0.20905     0.0408463   0.231149
 -0.262421    0.0419209    0.0885483     -0.264767   -0.289394    0.380493
 -0.2616      0.157511    -0.0602512      0.352425    0.154028   -0.0550213
 -0.0353826  -0.166718    -0.387146   …   0.198684    0.0713574   0.0517334

In [54]:
cum_r = cumprod(returns .+ 1,dims=1)

6×2×5 Array{Float64, 3}:
[:, :, 1] =
 1.0403   1.18361
 1.07687  1.23181
 1.11071  1.39273
 1.16191  1.62666
 1.18326  1.33649
 1.23414  1.3795

[:, :, 2] =
 1.0403   1.0578
 1.05405  1.04122
 1.06702  1.05656
 1.11386  1.22344
 1.14403  1.06068
 1.20157  1.03453

[:, :, 3] =
 1.0403   0.957966
 1.08182  1.02604
 1.12538  1.24347
 1.16521  1.49022
 1.17954  1.85698
 1.19405  1.8955

[:, :, 4] =
 1.0403   1.04823
 1.05699  1.05094
 1.07     1.12378
 1.08316  1.06413
 1.11962  0.897635
 1.13339  1.14894

[:, :, 5] =
 1.0403   0.902723
 1.1081   1.15435
 1.16619  1.44231
 1.24924  1.5776
 1.31255  1.69074
 1.3587   1.70398

In [55]:
function take_cumulative_returns_in_periods(r,timestamps)
    cum_r = cumprod(r .+ 1,dims=1)
    end_index = cumsum(timestamps)
    start_index = end_index - timestamps .+ 1
    n_scenarios = size(r,3)
    n_assets = size(r,2)
    t = length(timestamps)
    result = zeros(t+1,n_assets,n_scenarios)
    result[1,:,:] .= 1

    for (index, dt) in enumerate(timestamps)
        result[index+1,:,:] = cum_r[end_index[index],:,:]
    end    
    return result
    
end

take_cumulative_returns_in_periods(returns, [2,2,2])

4×2×5 Array{Float64, 3}:
[:, :, 1] =
 1.0      1.0
 1.07687  1.23181
 1.16191  1.62666
 1.23414  1.3795

[:, :, 2] =
 1.0      1.0
 1.05405  1.04122
 1.11386  1.22344
 1.20157  1.03453

[:, :, 3] =
 1.0      1.0
 1.08182  1.02604
 1.16521  1.49022
 1.19405  1.8955

[:, :, 4] =
 1.0      1.0
 1.05699  1.05094
 1.08316  1.06413
 1.13339  1.14894

[:, :, 5] =
 1.0      1.0
 1.1081   1.15435
 1.24924  1.5776
 1.3587   1.70398

In [56]:
tc_returns = take_cumulative_returns_in_periods(r_long,[5,5,5,5])

using Statistics

describe(tc_returns[end,2,:])

Summary Stats:
Length:         99999
Missing Count:  0
Mean:           4.952773
Std. Deviation: 3.952577
Minimum:        0.073572
1st Quartile:   2.282939
Median:         3.878178
3rd Quartile:   6.397595
Maximum:        55.105188
Type:           Float64


In [57]:
function create_sampler(returns)
    function sampler()
        s = size(returns,3)
        rnd = rand(1:s)
        return returns[:,:,rnd]
    end
end 

sample = create_sampler(tc_returns)

sample()

5×2 Matrix{Float64}:
 1.0      1.0
 1.15758  1.38395
 1.32457  2.03409
 1.47743  2.4567
 1.58519  5.57896

In [58]:
tree = Tree([1,8,4,2,2],2)

tree_approximation!(tree, create_sampler(tc_returns), 100000, 2, 2)
tree.name

"Tree 1x8x4x2x2 with d=[0.5126917851663632; 0.5126917851663632;;] at 100000 iterations"

In [59]:
tree.state[nodes(tree,1),:]

8×2 Matrix{Float64}:
 1.16156  1.52099
 1.42487  1.45185
 1.19686  1.52318
 1.355    1.52697
 1.12046  1.49745
 1.2326   1.53021
 1.26786  1.50151
 1.3079   1.53477

In [60]:
tree.probability[nodes(tree,1),:]

8×1 Matrix{Float64}:
 0.17728
 0.02368
 0.17964000000000002
 0.06896
 0.14034000000000002
 0.16509000000000001
 0.1391
 0.10591

In [61]:
lattice = lattice_approximation([1,12,12,12,12],create_sampler(tc_returns),1000000,2,2);


In [62]:
infl = lattice[1]
infl.name

"Lattice 1 with distance=0.23796426337149956"

In [63]:
infl.state

5-element Vector{Array{Float64, 3}}:
 [1.0;;;]
 [1.251631; 1.173525; … ; 1.18602; 1.18602;;;]
 [1.419701; 1.68131; … ; 1.607746; 1.607746;;;]
 [1.684231; 2.217175; … ; 2.099349; 2.099349;;;]
 [1.985181; 2.846797; … ; 2.577443; 2.577443;;;]

In [64]:
infl.state[2] .^(1/5) .-1

12×1×1 Array{Float64, 3}:
[:, :, 1] =
 0.045912280383949344
 0.03251999158426444
 0.034786878497289564
 0.03470907009212487
 0.03470941906098446
 0.03470941906098446
 0.03470941906098446
 0.03470941906098446
 0.03470941906098446
 0.03470941906098446
 0.03470941906098446
 0.03470941906098446

In [65]:
infl.probability[2]

1×12×1 Array{Float64, 3}:
[:, :, 1] =
 0.470485  0.339326  0.159225  0.029831  …  0.0  0.0  0.0  0.0  0.0  0.0

In [66]:
eq = lattice[2]
eq.name

"Lattice 2 with distance=1.5329839475488622"

In [67]:
eq.state

5-element Vector{Array{Float64, 3}}:
 [1.0;;;]
 [2.209778; 0.923989; … ; 1.18602; 1.18602;;;]
 [4.762646; 1.012536; … ; 1.607746; 1.607746;;;]
 [9.836943; 1.156203; … ; 2.099349; 2.099349;;;]
 [20.511386; 1.308523; … ; 2.577443; 2.577443;;;]

In [68]:
eq.state[2] .^(1/5) .-1

12×1×1 Array{Float64, 3}:
[:, :, 1] =
  0.17184380676955802
 -0.015686684385830096
  0.07207513816143774
  0.03497432505399667
  0.03402540922736974
  0.03470941906098446
  0.03470941906098446
  0.03470941906098446
  0.03470941906098446
  0.03470941906098446
  0.03470941906098446
  0.03470941906098446

In [69]:
eq.probability

5-element Vector{Array{Float64, 3}}:
 [1.0;;;]
 [0.291744 0.196489 … 0.0 0.0;;;]
 [0.092896 0.008028 … 0.0 0.0; 2.5e-5 0.118382 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]
 [0.042005 0.000199 … 0.0 0.0; 0.0 0.139633 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]
 [0.020742 0.0 … 0.0 0.0; 0.0 0.138552 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]

In [70]:
eq.probability[2]

1×12×1 Array{Float64, 3}:
[:, :, 1] =
 0.291744  0.196489  0.354332  0.073015  …  0.000296  0.0  0.0  0.0  0.0  0.0

In [92]:
eq_returns = permutedims(take_returns_in_periods(transpose(equity),[1,1,1,1,1,1,1,1,1,1,1]),(2,3,1))

99999×1×11 Array{Float64, 3}:
[:, :, 1] =
  0.1685674005612916
  0.056187498209429684
 -0.04294299224651092
  0.04710588943186373
 -0.1023395278844141
  0.15579104797319118
  0.09257644655826903
  0.22703357535033372
  0.23411672522165797
  0.06320857465067069
  ⋮
  0.26549704449148204
  0.23199783618381395
 -0.05215261086263971
  0.3152216043287681
 -0.14899084801808318
 -0.13929425175946672
  0.1125381943799319
 -0.15691232298913244
 -0.025654274839324368

[:, :, 2] =
  0.039919507401237564
 -0.015793056379841398
  0.0686506796126563
  0.0025816646342105443
  0.24587287205411515
  0.05666195729245451
  0.19413154355331244
  0.053397628722160285
  0.1937740591523814
 -0.23147692764322855
  ⋮
 -0.0046347237585427714
  0.09019073413976995
  0.1921307885842072
  0.24670381572322284
  0.060714029584147136
  0.2641557357472168
  0.09145913768766871
 -0.5000043851344074
  0.01408730631201215

[:, :, 3] =
  0.1227820751665497
  0.01462256725463752
  0.1922009280338393
  0.06700796953846366
 

In [83]:
print(fill(3,11))

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [127]:
function normal()
  μ = 0.08
  σ = .15
  steps = 11
  #return rand(Normal(μ,σ),steps)
  return cumsum(randn(Normal(μ,σ), 11,1), dims = 1)
end    

normal()

MethodError: MethodError: no method matching randn(::Normal{Float64}, ::Int64, ::Int64)

Closest candidates are:
  randn(!Matched::Type{T}, ::Integer...) where T
   @ Random C:\Users\matsz\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Random\src\normal.jl:254
  randn(!Matched::Random.AbstractRNG, ::Integer...)
   @ Random C:\Users\matsz\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Random\src\normal.jl:256
  randn(!Matched::Integer...)
   @ Random C:\Users\matsz\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Random\src\normal.jl:258
  ...


In [121]:
lattice = lattice_approximation([1,3, 3, 3, 3, 3, 3, 3, 3, 3, 3,3],gaussian_path1D,1000000,2,1);

BoundsError: BoundsError: attempt to access 4×1 Matrix{Float64} at index [5]