In [40]:
import Pkg
Pkg.add("ScenTrees")
Pkg.add("FinanceModels")
Pkg.add("EconomicScenarioGenerators")
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("CSV")
Pkg.add("DataFrames")


   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  No 

Pkg.Types.PkgError: The following package names could not be resolved:
 * Iterators (not found in project, manifest or registry)
   Suggestions: IteratorSampling TarIterators BatchIterators MergedIterators

In [195]:
using  CSV, DataFrames, LinearAlgebra, ScenTrees

In [143]:
inflation_source = CSV.read("../sb_gbi/inflation_scenarios.csv",DataFrame)
equity_source = CSV.read("../sb_gbi/equity_scenarios.csv",DataFrame)
println(describe(inflation_source))
println(describe(equity_source))

51×7 DataFrame
 Row │ variable    mean       min      median    max       nmissing  eltype   
     │ Symbol      Float64    Float64  Float64   Float64   Int64     DataType 
─────┼────────────────────────────────────────────────────────────────────────
   1 │ 0.040300    0.0403      0.0403  0.0403    0.0403           0  Float64
   2 │ 0.014355    0.0404836   0.0123  0.038629  0.161131         0  Float64
   3 │ 0.090209    0.0405224   0.0123  0.03794   0.168142         0  Float64
   4 │ 0.047505    0.0403158   0.0123  0.03751   0.158611         0  Float64
   5 │ 0.012300    0.0402553   0.0123  0.037425  0.165503         0  Float64
   6 │ 0.012300_1  0.0402959   0.0123  0.037519  0.164738         0  Float64
   7 │ 0.033621    0.0402064   0.0123  0.037467  0.162832         0  Float64
   8 │ 0.014701    0.0402702   0.0123  0.037353  0.152392         0  Float64
   9 │ 0.042845    0.0402596   0.0123  0.037286  0.175204         0  Float64
  10 │ 0.045539    0.0402009   0.0123  0.037396  0.1614

In [144]:
inflation = Matrix(inflation_source[1:5,1:6])
equity = Matrix(equity_source[1:5,1:6])

returns = cat(inflation,equity,dims=3)
returns = permutedims(returns,(2,3,1))

6×2×5 Array{Float64, 3}:
[:, :, 1] =
 0.0403     0.183608
 0.035158   0.040727
 0.031416   0.130638
 0.046096   0.167958
 0.018379  -0.178384
 0.043002   0.032183

[:, :, 2] =
 0.0403     0.057796
 0.013222  -0.015669
 0.0123     0.01473
 0.043899   0.15795
 0.027086  -0.133039
 0.050294  -0.024649

[:, :, 3] =
 0.0403    -0.042034
 0.039912   0.071062
 0.040263   0.211914
 0.035394   0.19843
 0.0123     0.246116
 0.0123     0.020742

[:, :, 4] =
 0.0403     0.048233
 0.016048   0.002585
 0.0123     0.069304
 0.0123    -0.053078
 0.03366   -0.156461
 0.0123     0.279966

[:, :, 5] =
 0.0403    -0.097277
 0.065174   0.278737
 0.052422   0.249458
 0.071214   0.093802
 0.05068    0.071716
 0.035161   0.007833

In [149]:
inflation = Matrix(inflation_source[:,1:50])
equity = Matrix(equity_source)

r_long = cat(inflation,equity,dims=3)
r_long = permutedims(r_long,(2,3,1)) 

50×2×99999 Array{Float64, 3}:
[:, :, 1] =
 0.0403     0.183608
 0.035158   0.040727
 0.031416   0.130638
 0.046096   0.167958
 0.018379  -0.178384
 0.043002   0.032183
 0.029849   0.122386
 0.043892  -0.049013
 0.033638  -0.230813
 0.027528  -0.230181
 ⋮         
 0.028233   0.204203
 0.027208   0.084194
 0.040718  -0.195554
 0.026403   0.164883
 0.0688     0.105274
 0.013082   0.357969
 0.019406   0.310636
 0.06628    0.259417
 0.09403    0.106576

[:, :, 2] =
 0.0403     0.057796
 0.013222  -0.015669
 0.0123     0.01473
 0.043899   0.15795
 0.027086  -0.133039
 0.050294  -0.024649
 0.071821  -0.002556
 0.091165   0.101583
 0.055169   0.042812
 0.0123     0.170594
 ⋮         
 0.076536   0.108522
 0.068139   0.101433
 0.026111   0.089037
 0.054689  -0.170575
 0.036394   0.116987
 0.020704   0.206452
 0.0123     0.181475
 0.019199   0.038817
 0.021789   0.09112

[:, :, 3] =
 0.0403    -0.042034
 0.039912   0.071062
 0.040263   0.211914
 0.035394   0.19843
 0.0123     0.246116
 0.0123  

In [150]:
size(r_long)

(50, 2, 99999)

In [270]:
using Base.Iterators

function take_returns_in_periods(r,timestamps)
    end_index = cumsum(timestamps)
    start_index = end_index - timestamps .+ 1
    n_scenarios = size(r,3)
    n_assets = size(r,2)
    t = length(timestamps)
    result = zeros(t,n_assets,n_scenarios)
    for (index, dt) in enumerate(timestamps)
        result[index,:,:] = sum(log1p.(r[start_index[index]:end_index[index],:,:]),dims=1)
    end    
    return result
    
end

t_returns = take_returns_in_periods(r_long,[1,1,1,1])
t_returns = t_returns .+ 1
t_returns = cumprod(t_returns,dims=1)

4×2×99999 Array{Float64, 3}:
[:, :, 1] =
 1.03951  1.16857
 1.07543  1.21522
 1.10869  1.36442
 1.15866  1.57626

[:, :, 2] =
 1.03951  1.05619
 1.05316  1.03951
 1.06604  1.05471
 1.11184  1.20938

[:, :, 3] =
 1.03951  0.957057
 1.08019  1.02276
 1.12283  1.21933
 1.16188  1.44005

;;; … 

[:, :, 99997] =
 1.03951  1.11254
 1.10471  1.21429
 1.16755  0.79461
 1.2092   0.81823

[:, :, 99998] =
 1.03951  0.843088
 1.06731  0.42154
 1.12895  0.446199
 1.18571  0.520427

[:, :, 99999] =
 1.03951  0.974346
 1.05222  0.988072
 1.08077  1.14682
 1.09398  1.23136

In [285]:
cum_r = cumprod(returns .+ 1,dims=1)

6×2×5 Array{Float64, 3}:
[:, :, 1] =
 1.0403   1.18361
 1.07687  1.23181
 1.11071  1.39273
 1.16191  1.62666
 1.18326  1.33649
 1.23414  1.3795

[:, :, 2] =
 1.0403   1.0578
 1.05405  1.04122
 1.06702  1.05656
 1.11386  1.22344
 1.14403  1.06068
 1.20157  1.03453

[:, :, 3] =
 1.0403   0.957966
 1.08182  1.02604
 1.12538  1.24347
 1.16521  1.49022
 1.17954  1.85698
 1.19405  1.8955

[:, :, 4] =
 1.0403   1.04823
 1.05699  1.05094
 1.07     1.12378
 1.08316  1.06413
 1.11962  0.897635
 1.13339  1.14894

[:, :, 5] =
 1.0403   0.902723
 1.1081   1.15435
 1.16619  1.44231
 1.24924  1.5776
 1.31255  1.69074
 1.3587   1.70398

In [290]:
function take_cumulative_returns_in_periods(r,timestamps)
    cum_r = cumprod(r .+ 1,dims=1)
    end_index = cumsum(timestamps)
    start_index = end_index - timestamps .+ 1
    n_scenarios = size(r,3)
    n_assets = size(r,2)
    t = length(timestamps)
    result = zeros(t+1,n_assets,n_scenarios)
    result[1,:,:] .= 1

    for (index, dt) in enumerate(timestamps)
        result[index+1,:,:] = cum_r[end_index[index],:,:]
    end    
    return result
    
end

take_cumulative_returns_in_periods(returns, [2,2,2])

4×2×5 Array{Float64, 3}:
[:, :, 1] =
 1.0      1.0
 1.07687  1.23181
 1.16191  1.62666
 1.23414  1.3795

[:, :, 2] =
 1.0      1.0
 1.05405  1.04122
 1.11386  1.22344
 1.20157  1.03453

[:, :, 3] =
 1.0      1.0
 1.08182  1.02604
 1.16521  1.49022
 1.19405  1.8955

[:, :, 4] =
 1.0      1.0
 1.05699  1.05094
 1.08316  1.06413
 1.13339  1.14894

[:, :, 5] =
 1.0      1.0
 1.1081   1.15435
 1.24924  1.5776
 1.3587   1.70398

In [320]:
tc_returns = take_cumulative_returns_in_periods(r_long,[5,5,5,5])

using Statistics

describe(tc_returns[end,2,:])

Summary Stats:
Length:         99999
Missing Count:  0
Mean:           4.952773
Std. Deviation: 3.952577
Minimum:        0.073572
1st Quartile:   2.282939
Median:         3.878178
3rd Quartile:   6.397595
Maximum:        55.105188
Type:           Float64


In [303]:
function create_sampler(returns)
    function sampler()
        s = size(returns,3)
        rnd = rand(1:s)
        return returns[:,:,rnd]
    end
end 

sample = create_sampler(tc_returns)

sample()

5×2 Matrix{Float64}:
 1.0      1.0
 1.12844  1.21129
 1.32473  2.38032
 1.61435  0.925464
 2.02817  1.36475

In [313]:
tree = Tree([1,8,4,2,2],2)

tree_approximation!(tree, create_sampler(tc_returns), 100000, 2, 2)
tree.name

"Tree 1x8x4x2x2 with d=[0.46820483031970134; 0.46820483031970134;;] at 100000 iterations"

In [325]:
tree.state[nodes(tree,1),:]

8×2 Matrix{Float64}:
 1.11566  1.60558
 1.18611  1.51155
 1.25396  1.49282
 1.1523   1.54569
 1.2949   1.51827
 1.2195   1.55224
 1.3432   1.52111
 1.42225  1.47247

In [324]:
tree.probability[nodes(tree,1),:]

8×1 Matrix{Float64}:
 0.10381
 0.16031
 0.1558
 0.14481
 0.13728
 0.16568
 0.09526000000000001
 0.03705000000000001

In [330]:
lattice = lattice_approximation([1,12,12,12,12],create_sampler(tc_returns),1000000,2,2);


In [331]:
infl = lattice[1]
infl.name

"Lattice 1 with distance=0.21939024199389504"

In [346]:
infl.state

5-element Vector{Array{Float64, 3}}:
 [1.0;;;]
 [1.20878; 1.302603; … ; 1.286596; 1.286596;;;]
 [1.413069; 1.661684; … ; 1.576028; 1.576028;;;]
 [1.646425; 2.115416; … ; 1.878277; 1.878277;;;]
 [2.691979; 1.918829; … ; 2.235342; 2.235342;;;]

In [344]:
infl.state[2] .^(1/5) .-1

12×1×1 Array{Float64, 3}:
[:, :, 1] =
 0.03865054456693828
 0.054295650433133336
 0.05169217328464093
 0.051593410361697734
 0.05169168283198822
 0.05169168283198822
 0.05169168283198822
 0.05169168283198822
 0.05169168283198822
 0.05169168283198822
 0.05169168283198822
 0.05169168283198822

In [345]:
infl.probability[2]

1×12×1 Array{Float64, 3}:
[:, :, 1] =
 0.678695  0.166758  0.020797  0.133031  …  0.0  0.0  0.0  0.0  0.0  0.0

In [347]:
eq = lattice[2]
eq.name

"Lattice 2 with distance=1.441478237803794"

In [349]:
eq.state

5-element Vector{Array{Float64, 3}}:
 [1.0;;;]
 [2.242584; 0.950915; … ; 1.286596; 1.286596;;;]
 [1.020693; 4.649101; … ; 1.576028; 1.576028;;;]
 [1.128223; 10.203443; … ; 1.878277; 1.878277;;;]
 [1.261627; 23.682682; … ; 2.235342; 2.235342;;;]

In [351]:
eq.state[2] .^(1/5) .-1

12×1×1 Array{Float64, 3}:
[:, :, 1] =
  0.17530272708933925
 -0.010015626187999005
  0.08103249368246646
  0.05017179603709332
  0.05183158822487499
  0.05169168283198822
  0.05169168283198822
  0.05169168283198822
  0.05169168283198822
  0.05169168283198822
  0.05169168283198822
  0.05169168283198822

In [352]:
eq.probability

5-element Vector{Array{Float64, 3}}:
 [1.0;;;]
 [0.26448 0.236408 … 0.0 0.0;;;]
 [0.006688 0.097267 … 0.0 0.0; 0.130779 0.000152 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]
 [0.126834 0.0 … 0.0 0.0; 0.000141 0.039529 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]
 [0.117142 0.0 … 0.0 0.0; 0.0 0.011977 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]

In [353]:
eq.probability[2]

1×12×1 Array{Float64, 3}:
[:, :, 1] =
 0.26448  0.236408  0.322622  0.112232  …  0.000193  0.0  0.0  0.0  0.0  0.0