In [2]:
import Pkg
Pkg.add("Clustering")

   Resolving package versions...
   Installed NearestNeighbors ─ v0.4.16
   Installed Clustering ─────── v0.15.7
    Updating `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  [aaaa29a8] + Clustering v0.15.7
    Updating `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
  [aaaa29a8] + Clustering v0.15.7
  [b8a86587] + NearestNeighbors v0.4.16
Precompiling project...
  ✓ NearestNeighbors
  ✓ Clustering
  2 dependencies successfully precompiled in 24 seconds. 395 already precompiled.


In [15]:
using Clustering
using CSV
using DataFrames
using Statistics

In [288]:
acwi = Matrix(CSV.read("../sb_gbi/equity_scenarios.csv",DataFrame))

99999×50 Matrix{Float64}:
  0.183608   0.040727   0.130638  …   0.310636   0.259417   0.106576
  0.057796  -0.015669   0.01473       0.181475   0.038817   0.09112
 -0.042034   0.071062   0.211914      0.271774   0.03051    0.014144
  0.048233   0.002585   0.069304      0.161997   0.150916  -0.458586
 -0.097277   0.278737   0.249458      0.054621   0.20249    0.148626
  0.168582   0.058298   0.174671  …  -0.057467  -0.037438   0.030723
  0.096997   0.214256  -0.246285      0.148997   0.192833   0.181174
  0.254872   0.054849   0.014113      0.13077    0.066608  -0.076274
  0.263792   0.213822   0.260164      0.309639   0.022386   0.268776
  0.065249  -0.206639   0.347267      0.165357   0.180862   0.298468
  ⋮                               ⋱                        
  0.304079  -0.004624   0.041851  …  -0.008278   0.136057   0.139732
  0.261117   0.094383  -0.240846      0.037133  -0.072158  -0.037526
 -0.050816   0.211829  -0.100711      0.158417  -0.021944   0.318735
  0.370563   0.279

In [48]:
inflation = Matrix(CSV.read("../sb_gbi/inflation_scenarios.csv", DataFrame))[:,2:end]

99999×50 Matrix{Float64}:
 0.035158  0.031416  0.046096  0.018379  …  0.06628   0.09403   0.093851
 0.013222  0.0123    0.043899  0.027086     0.019199  0.021789  0.020151
 0.039912  0.040263  0.035394  0.0123       0.02551   0.0123    0.0123
 0.016048  0.0123    0.0123    0.03366      0.056582  0.0123    0.0123
 0.065174  0.052422  0.071214  0.05068      0.019615  0.058837  0.048566
 0.051986  0.035766  0.026192  0.033541  …  0.052188  0.046143  0.026802
 0.040925  0.025968  0.043467  0.024486     0.0786    0.047548  0.027347
 0.0123    0.045685  0.022954  0.0123       0.019471  0.048676  0.043244
 0.0123    0.014093  0.0123    0.0123       0.037708  0.071717  0.083529
 0.0123    0.046767  0.048754  0.071964     0.058765  0.0123    0.024597
 ⋮                                       ⋱                      
 0.05639   0.034089  0.038381  0.037493  …  0.037054  0.031733  0.02699
 0.022314  0.042175  0.031607  0.039552     0.060712  0.045391  0.080075
 0.078099  0.090769  0.052886  0.02624

In [73]:
returns = stack([acwi,inflation],dims=1)

2×99999×50 Array{Float64, 3}:
[:, :, 1] =
 0.183608  0.057796  -0.042034  0.048233  …  0.119115  -0.145221  -0.025328
 0.035158  0.013222   0.039912  0.016048     0.064728   0.027103   0.0123

[:, :, 2] =
 0.040727  -0.015669  0.071062  0.002585  …  0.095772  -0.393472  0.014187
 0.031416   0.0123    0.040263  0.0123       0.058533   0.059451  0.027505

[:, :, 3] =
 0.130638  0.01473   0.211914  0.069304  …  -0.292217  0.060243  0.174296
 0.046096  0.043899  0.035394  0.0123        0.036324  0.051567  0.0123

;;; … 

[:, :, 48] =
 0.310636  0.181475  0.271774  0.161997  …  0.084165  0.142273  0.012147
 0.06628   0.019199  0.02551   0.056582     0.0123    0.04997   0.065018

[:, :, 49] =
 0.259417  0.038817  0.03051  0.150916  …  0.118251  0.023003  0.20869
 0.09403   0.021789  0.0123   0.0123       0.035531  0.0123    0.095034

[:, :, 50] =
 0.106576  0.09112   0.014144  -0.458586  …  0.292593  0.115302  0.170179
 0.093851  0.020151  0.0123     0.0123       0.045336  0.0123    0.057752

In [124]:
period_1 = returns[:,:,1] 


2×99999 Matrix{Float64}:
 0.183608  0.057796  -0.042034  0.048233  …  0.119115  -0.145221  -0.025328
 0.035158  0.013222   0.039912  0.016048     0.064728   0.027103   0.0123

In [131]:
period_1[:,1]

2-element Vector{Float64}:
 0.183608
 0.035158

In [253]:
n_clusters = 12
result = kmeans(period_1,n_clusters)

KmeansResult{Matrix{Float64}, Float64, Int64}([0.16818623502048105 -0.25860468448365365 … 0.11123793435571366 -0.14583081772973008; 0.038084508088591464 0.04035417799688653 … 0.02504347007667944 0.041094225945946285], [1, 10, 4, 10, 4, 1, 11, 6, 6, 10  …  5, 6, 6, 4, 7, 12, 12, 8, 12, 5], [0.0002463952846761125, 0.0007065127247324913, 0.0004796971328582065, 0.0006217363692727403, 0.0017137370277039467, 0.00019340810728196017, 0.0004550272040290751, 0.001495108576262394, 0.001109426810356251, 0.0008385633488134266  …  0.0006093306147079468, 0.0007764560599860526, 0.0007369002390351653, 0.0015740054839335008, 0.0003045023600265484, 0.00042956046529659536, 0.0005190573852479757, 1.5911843333313302e-5, 0.0001961262811340167, 0.0014530249643849961], [14399, 1928, 1550, 7706, 10977, 8996, 5110, 7774, 12553, 13683, 10696, 4627], [14403, 1927, 1552, 7702, 10974, 8994, 5111, 7771, 12556, 13690, 10694, 4625], 81.81665448519425, 100, false)

In [254]:
counts(result)

12-element Vector{Int64}:
 14399
  1928
  1550
  7706
 10977
  8996
  5110
  7774
 12553
 13683
 10696
  4627

In [255]:
centers =result.centers

2×12 Matrix{Float64}:
 0.168186   -0.258605   0.46345    …  0.0560013  0.111238   -0.145831
 0.0380845   0.0403542  0.0402921     0.0397417  0.0250435   0.0410942

In [256]:
for cluster in 1:n_clusters
    println("equity: $(centers[1,cluster]), infl: $(centers[2,cluster])")
end

equity: 0.16818623502048105, infl: 0.038084508088591464
equity: -0.25860468448365365, infl: 0.04035417799688653
equity: 0.46345026353092805, infl: 0.04029209536082492
equity: -0.06392344949363808, infl: 0.04065303557517541
equity: 0.0004009842354656465, infl: 0.04042551038818952
equity: 0.2809509330664888, infl: 0.04084816677785154
equity: 0.3542111700254347, infl: 0.039964619839562274
equity: 0.11526165062411567, infl: 0.06575928168832836
equity: 0.22144475390251625, infl: 0.04126747610703937
equity: 0.05600134733382003, infl: 0.03974165208181026
equity: 0.11123793435571366, infl: 0.02504347007667944
equity: -0.14583081772973008, infl: 0.041094225945946285


In [257]:
clusters = assignments(result)

99999-element Vector{Int64}:
  1
 10
  4
 10
  4
  1
 11
  6
  6
 10
  ⋮
  6
  6
  4
  7
 12
 12
  8
 12
  5

In [277]:
cluster_means = zeros((2,n_clusters))

for cluster in 1:n_clusters
    cluster_means[:,cluster] = mean(period_1[:,clusters .== cluster],dims=2) 
end


for cluster in 1:n_clusters
    println("$(cluster_means[1,cluster]), $(cluster_means[2,cluster])")
end

0.16820545843461276, 0.03807259073546654
-0.25857561410788404, 0.04038113485477196
0.4635209264516131, 0.040231969677419537
-0.06387829781988069, 0.040652384505580196
0.00044675639974492144, 0.040420502778536205
0.28096651445086696, 0.0408534413072473
0.35425390606653556, 0.039974964383562184
0.11529385914587123, 0.06576677180344734
0.22145541233171304, 0.04127046004938951
0.056027915515603016, 0.039744148578526824
0.11124786415482439, 0.025046461293942585
-0.14579200972552442, 0.041083429435919944


In [281]:
probs = counts(result)/sum(counts(result))

12-element Vector{Float64}:
 0.14399143991439914
 0.01928019280192802
 0.015500155001550015
 0.07706077060770608
 0.10977109771097711
 0.08996089960899609
 0.05110051100511005
 0.07774077740777408
 0.12553125531255313
 0.13683136831368314
 0.10696106961069611
 0.04627046270462705

In [287]:
scenario_period1 = DataFrame(Equity=cluster_means[1,:].*100,EDO=cluster_means[2,:].*100,Probs=probs*100)

12×3 DataFrame
 Row │ Equity       EDO      Probs    
     │ Float64      Float64  Float64  
─────┼────────────────────────────────
   1 │  16.8205     3.80726  14.3991
   2 │ -25.8576     4.03811   1.92802
   3 │  46.3521     4.0232    1.55002
   4 │  -6.38783    4.06524   7.70608
   5 │   0.0446756  4.04205  10.9771
   6 │  28.0967     4.08534   8.99609
   7 │  35.4254     3.9975    5.11005
   8 │  11.5294     6.57668   7.77408
   9 │  22.1455     4.12705  12.5531
  10 │   5.60279    3.97441  13.6831
  11 │  11.1248     2.50465  10.6961
  12 │ -14.5792     4.10834   4.62705

In [259]:
quantile(acwi[:,1],[0.01, 0.05,0.25,0.5,0.75,0.95,0.99])

7-element Vector{Float64}:
 -0.24365456
 -0.12870330000000002
  0.0271735
  0.119023
  0.207915
  0.3375451
  0.43165099999999945

In [260]:
sort(cluster_means[1,:])

12-element Vector{Float64}:
 -0.25857561410788404
 -0.14579200972552442
 -0.06387829781988069
  0.00044675639974492144
  0.056027915515603016
  0.11124786415482439
  0.11529385914587123
  0.16820545843461276
  0.22145541233171304
  0.28096651445086696
  0.35425390606653556
  0.4635209264516131

In [261]:
sort(cluster_means[2,:])

12-element Vector{Float64}:
 0.025046461293942585
 0.03807259073546654
 0.039744148578526824
 0.039974964383562184
 0.040231969677419537
 0.04038113485477196
 0.040420502778536205
 0.040652384505580196
 0.0408534413072473
 0.041083429435919944
 0.04127046004938951
 0.06576677180344734

In [262]:
quantile(inflation[:,1],[0.01, 0.05,0.25,0.5,0.75,0.95,0.99])

7-element Vector{Float64}:
 0.0123
 0.0123
 0.021725
 0.038629
 0.0554615
 0.079651
 0.09682603999999997

In [297]:
acwi_1 = acwi[:,1]
acwi_1 = reshape(acwi_1,99999,1)

99999×1 Matrix{Float64}:
  0.183608
  0.057796
 -0.042034
  0.048233
 -0.097277
  0.168582
  0.096997
  0.254872
  0.263792
  0.065249
  ⋮
  0.304079
  0.261117
 -0.050816
  0.370563
 -0.138423
 -0.130028
  0.119115
 -0.145221
 -0.025328

In [303]:
n_clusters = 4
result_acwi = kmeans(acwi_1,1)

KmeansResult{Matrix{Float64}, Float64, Int64}([0.183608; 0.057796; … ; -0.145221; -0.025328;;], [1], [0.0], [1], [1], 0.0, 0, true)

In [304]:
result_acwi.centers

99999×1 Matrix{Float64}:
  0.183608
  0.057796
 -0.042034
  0.048233
 -0.097277
  0.168582
  0.096997
  0.254872
  0.263792
  0.065249
  ⋮
  0.304079
  0.261117
 -0.050816
  0.370563
 -0.138423
 -0.130028
  0.119115
 -0.145221
 -0.025328