In [2]:
import Pkg
Pkg.add("Clustering")

   Resolving package versions...
   Installed NearestNeighbors ─ v0.4.16
   Installed Clustering ─────── v0.15.7
    Updating `C:\Users\matsz\.julia\environments\v1.10\Project.toml`
  [aaaa29a8] + Clustering v0.15.7
    Updating `C:\Users\matsz\.julia\environments\v1.10\Manifest.toml`
  [aaaa29a8] + Clustering v0.15.7
  [b8a86587] + NearestNeighbors v0.4.16
Precompiling project...
  ✓ NearestNeighbors
  ✓ Clustering
  2 dependencies successfully precompiled in 24 seconds. 395 already precompiled.


In [1]:
using Clustering
using CSV
using DataFrames
using Statistics

In [2]:
acwi = Matrix(CSV.read("../sb_gbi/equity_scenarios.csv",DataFrame))

99999×50 Matrix{Float64}:
  0.183608   0.040727   0.130638  …   0.310636   0.259417   0.106576
  0.057796  -0.015669   0.01473       0.181475   0.038817   0.09112
 -0.042034   0.071062   0.211914      0.271774   0.03051    0.014144
  0.048233   0.002585   0.069304      0.161997   0.150916  -0.458586
 -0.097277   0.278737   0.249458      0.054621   0.20249    0.148626
  0.168582   0.058298   0.174671  …  -0.057467  -0.037438   0.030723
  0.096997   0.214256  -0.246285      0.148997   0.192833   0.181174
  0.254872   0.054849   0.014113      0.13077    0.066608  -0.076274
  0.263792   0.213822   0.260164      0.309639   0.022386   0.268776
  0.065249  -0.206639   0.347267      0.165357   0.180862   0.298468
  ⋮                               ⋱                        
  0.304079  -0.004624   0.041851  …  -0.008278   0.136057   0.139732
  0.261117   0.094383  -0.240846      0.037133  -0.072158  -0.037526
 -0.050816   0.211829  -0.100711      0.158417  -0.021944   0.318735
  0.370563   0.279

In [3]:
inflation = Matrix(CSV.read("../sb_gbi/inflation_scenarios.csv", DataFrame))[:,2:end]

99999×50 Matrix{Float64}:
 0.035158  0.031416  0.046096  0.018379  …  0.06628   0.09403   0.093851
 0.013222  0.0123    0.043899  0.027086     0.019199  0.021789  0.020151
 0.039912  0.040263  0.035394  0.0123       0.02551   0.0123    0.0123
 0.016048  0.0123    0.0123    0.03366      0.056582  0.0123    0.0123
 0.065174  0.052422  0.071214  0.05068      0.019615  0.058837  0.048566
 0.051986  0.035766  0.026192  0.033541  …  0.052188  0.046143  0.026802
 0.040925  0.025968  0.043467  0.024486     0.0786    0.047548  0.027347
 0.0123    0.045685  0.022954  0.0123       0.019471  0.048676  0.043244
 0.0123    0.014093  0.0123    0.0123       0.037708  0.071717  0.083529
 0.0123    0.046767  0.048754  0.071964     0.058765  0.0123    0.024597
 ⋮                                       ⋱                      
 0.05639   0.034089  0.038381  0.037493  …  0.037054  0.031733  0.02699
 0.022314  0.042175  0.031607  0.039552     0.060712  0.045391  0.080075
 0.078099  0.090769  0.052886  0.02624

In [4]:
returns = stack([acwi,inflation],dims=1)

2×99999×50 Array{Float64, 3}:
[:, :, 1] =
 0.183608  0.057796  -0.042034  0.048233  …  0.119115  -0.145221  -0.025328
 0.035158  0.013222   0.039912  0.016048     0.064728   0.027103   0.0123

[:, :, 2] =
 0.040727  -0.015669  0.071062  0.002585  …  0.095772  -0.393472  0.014187
 0.031416   0.0123    0.040263  0.0123       0.058533   0.059451  0.027505

[:, :, 3] =
 0.130638  0.01473   0.211914  0.069304  …  -0.292217  0.060243  0.174296
 0.046096  0.043899  0.035394  0.0123        0.036324  0.051567  0.0123

;;; … 

[:, :, 48] =
 0.310636  0.181475  0.271774  0.161997  …  0.084165  0.142273  0.012147
 0.06628   0.019199  0.02551   0.056582     0.0123    0.04997   0.065018

[:, :, 49] =
 0.259417  0.038817  0.03051  0.150916  …  0.118251  0.023003  0.20869
 0.09403   0.021789  0.0123   0.0123       0.035531  0.0123    0.095034

[:, :, 50] =
 0.106576  0.09112   0.014144  -0.458586  …  0.292593  0.115302  0.170179
 0.093851  0.020151  0.0123     0.0123       0.045336  0.0123    0.057752

In [5]:
period_1 = returns[:,:,1] 


2×99999 Matrix{Float64}:
 0.183608  0.057796  -0.042034  0.048233  …  0.119115  -0.145221  -0.025328
 0.035158  0.013222   0.039912  0.016048     0.064728   0.027103   0.0123

In [6]:
period_1[:,1]

2-element Vector{Float64}:
 0.183608
 0.035158

In [36]:
n_clusters = 8
result = kmeans(period_1,n_clusters)

KmeansResult{Matrix{Float64}, Float64, Int64}([0.2934456596854095 -0.004574761044176742 … -0.22443359634649368 0.21067259321284412; 0.04065370817763006 0.0404033514056214 … 0.040916105185621575 0.040523216050404716], [8, 3, 2, 3, 6, 4, 3, 1, 1, 3  …  2, 1, 1, 6, 5, 6, 6, 4, 6, 2], [0.0007612777490442618, 0.0008767934436819703, 0.0014034360093532735, 0.0010555228545998246, 0.0006027699914391248, 0.0010059892861607259, 0.000733399101235873, 0.0022918599889479863, 0.0016832723001602712, 0.0008022157099152032  …  0.0006543155507749104, 0.00036069880656469655, 0.001381487133095688, 0.0034152418543370693, 0.001599857511279612, 0.002216422304996357, 0.0014341116040871849, 0.0009804129044085688, 0.0026364967347345357, 0.0012204952873853423], [11493, 14452, 19330, 20837, 4006, 8394, 3399, 18088], [11507, 14442, 19328, 20835, 4012, 8388, 3394, 18093], 120.67075122945576, 100, false)

In [37]:
counts(result)

8-element Vector{Int64}:
 11493
 14452
 19330
 20837
  4006
  8394
  3399
 18088

In [38]:
centers =result.centers

2×8 Matrix{Float64}:
 0.293446   -0.00457476  0.0699245  …  -0.0956999  -0.224434   0.210673
 0.0406537   0.0404034   0.0402349      0.0406733   0.0409161  0.0405232

In [39]:
for cluster in 1:n_clusters
    println("equity: $(centers[1,cluster]), infl: $(centers[2,cluster])")
end

equity: 0.2934456596854095, infl: 0.04065370817763006
equity: -0.004574761044176742, infl: 0.0404033514056214
equity: 0.06992445312500013, infl: 0.04023485006208428
equity: 0.1390011300215991, infl: 0.04054216246700111
equity: 0.41005131779661014, infl: 0.040238338733798715
equity: -0.09569986540295648, infl: 0.040673333929422795
equity: -0.22443359634649368, infl: 0.040916105185621575
equity: 0.21067259321284412, infl: 0.040523216050404716


In [40]:
clusters = assignments(result)

99999-element Vector{Int64}:
 8
 3
 2
 3
 6
 4
 3
 1
 1
 3
 ⋮
 1
 1
 6
 5
 6
 6
 4
 6
 2

In [41]:
cluster_means = zeros((2,n_clusters))

for cluster in 1:n_clusters
    cluster_means[:,cluster] = mean(period_1[:,clusters .== cluster],dims=2) 
end


for cluster in 1:n_clusters
    println("$(cluster_means[1,cluster]), $(cluster_means[2,cluster])")
end

0.29354821239015105, 0.04064725850517612
-0.00448599813174649, 0.0403949309438129
0.07000607827211602, 0.040233171908947984
0.13908219330997826, 0.04054832053558422
0.4101387009485771, 0.040232542685971144
-0.09560185632594698, 0.040677227186085116
-0.22433900882612523, 0.040899589290967826
0.21076788047324127, 0.04053126603272736


In [42]:
probs = counts(result)/sum(counts(result))

8-element Vector{Float64}:
 0.11493114931149312
 0.14452144521445215
 0.19330193301933019
 0.2083720837208372
 0.04006040060400604
 0.08394083940839409
 0.03399033990339903
 0.18088180881808819

In [43]:
scenario_period1 = DataFrame(Equity=cluster_means[1,:].*100,EDO=cluster_means[2,:].*100,Probs=probs*100)

8×3 DataFrame
 Row │ Equity     EDO      Probs    
     │ Float64    Float64  Float64  
─────┼──────────────────────────────
   1 │  29.3548   4.06473  11.4931
   2 │  -0.4486   4.03949  14.4521
   3 │   7.00061  4.02332  19.3302
   4 │  13.9082   4.05483  20.8372
   5 │  41.0139   4.02325   4.00604
   6 │  -9.56019  4.06772   8.39408
   7 │ -22.4339   4.08996   3.39903
   8 │  21.0768   4.05313  18.0882

In [24]:
quantile(acwi[:,1],[0.01, 0.05,0.25,0.5,0.75,0.95,0.99])

7-element Vector{Float64}:
 -0.24365456
 -0.12870330000000002
  0.0271735
  0.119023
  0.207915
  0.3375451
  0.43165099999999945

In [25]:
sort(cluster_means[1,:])

4-element Vector{Float64}:
 0.002427294170323284
 0.1141016466473937
 0.22301709649547785
 0.2824087767625497

In [26]:
sort(cluster_means[2,:])

4-element Vector{Float64}:
 0.024899468059312733
 0.04054753926748374
 0.04084875702199625
 0.04128621907299637

In [27]:
quantile(inflation[:,1],[0.01, 0.05,0.25,0.5,0.75,0.95,0.99])

7-element Vector{Float64}:
 0.0123
 0.0123
 0.021725
 0.038629
 0.0554615
 0.079651
 0.09682603999999997

In [19]:
acwi_1 = acwi[:,1]
acwi_1 = reshape(acwi_1,99999,1)

99999×1 Matrix{Float64}:
  0.183608
  0.057796
 -0.042034
  0.048233
 -0.097277
  0.168582
  0.096997
  0.254872
  0.263792
  0.065249
  ⋮
  0.304079
  0.261117
 -0.050816
  0.370563
 -0.138423
 -0.130028
  0.119115
 -0.145221
 -0.025328

In [20]:
n_clusters = 4
result_acwi = kmeans(acwi_1,1)

KmeansResult{Matrix{Float64}, Float64, Int64}([0.183608; 0.057796; … ; -0.145221; -0.025328;;], [1], [0.0], [1], [1], 0.0, 0, true)

In [21]:
result_acwi.centers

99999×1 Matrix{Float64}:
  0.183608
  0.057796
 -0.042034
  0.048233
 -0.097277
  0.168582
  0.096997
  0.254872
  0.263792
  0.065249
  ⋮
  0.304079
  0.261117
 -0.050816
  0.370563
 -0.138423
 -0.130028
  0.119115
 -0.145221
 -0.025328