In [1]:
using Revise
using Test

In [2]:
includet("tvp-var.jl")

In [3]:
coef = generate_coeffs([0.03 0.05; 0.2 0.4], [0.8 0.8; 0.8 0.8], [0.001 0.001; 0.001 0.001], [0.01 0.02; 0.01 0.02], 8)



8×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.0365968  0.192449
 0.0291533  0.196183
 0.0287505  0.190696
 0.0275426  0.206376
 0.0284114  0.207423
 0.0364869  0.198989
 0.0415039  0.194783
 0.0369918  0.190801

[:, :, 2] =
 0.0664064  0.399857
 0.0595236  0.411104
 0.0446536  0.417246
 0.0438147  0.453049
 0.0483545  0.45205
 0.0720836  0.459659
 0.0955081  0.488232
 0.0941443  0.485894

In [4]:
round.(coef[8, :, :], digits=3)

2×2 Matrix{Float64}:
 0.037  0.094
 0.191  0.486

In [5]:
coef = generate_coeffs([0.03 0.05], [0.6 0.6], [0.001 0.001], [0.01 0.02], 8)

round.(coef[2, :, :], digits=3)

1×2 Matrix{Float64}:
 0.03  0.046

In [6]:
@test(residuals([0 0], [0.52 -0.35], [0.3 0.25]) == [-0.156 0.0875])


Error During Test at c:\Users\matsz\programowanie\Optymalizacja_portfela\julia_msp\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_W6sZmlsZQ==.jl:1
  Test threw exception
  Expression: residuals([0 0], [0.52 -0.35], [0.3 0.25]) == [-0.156 0.0875]
  DimensionMismatch: A has dimensions (1,2) but B has dimensions (1,2)
  Stacktrace:
   [1] gemm_wrapper!(C::Matrix{Float64}, tA::Char, tB::Char, A::Matrix{Float64}, B::Matrix{Float64}, _add::LinearAlgebra.MulAddMul{true, true, Bool, Bool})
     @ LinearAlgebra C:\Users\matsz\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:577
   [2] generic_matmatmul!
     @ C:\Users\matsz\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:352 [inlined]
   [3] mul!
     @ C:\Users\matsz\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:263 [inlined]
   [4] mul!
     @ C:\Users\matsz\.julia\juliaup\julia-1.10.2+0

Test.FallbackTestSetException: Test.FallbackTestSetException("There was an error during testing")

In [7]:
k_gain([0.0 0.0; 0.0 0.0], [0.45 -0.36; 0.45 -0.36], diagm([0.09, 0.12]))

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [8]:
Β = generate_coeffs([0.03 0.05; 0.2 0.4], [0.8 0.8; 0.8 0.8], [0.001 0.001; 0.001 0.001], [0.01 0.02; 0.01 0.02], 10)

10×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.013416   0.196836
 0.0139441  0.201809
 0.0224345  0.196965
 0.0246831  0.200711
 0.026805   0.200829
 0.0270879  0.209903
 0.0329985  0.206021
 0.0340881  0.205957
 0.0364829  0.194397
 0.0221373  0.182834

[:, :, 2] =
  0.0394798   0.398401
  0.0557359   0.397609
  0.0586413   0.399075
  0.0466846   0.405445
  0.0380141   0.376369
  0.0170884   0.377395
  0.0170622   0.360645
 -0.0117183   0.359693
 -0.00424383  0.3706
 -0.00301466  0.368709

In [9]:
round.(rand(Uniform(-1,1),2), digits=2)

2-element Vector{Float64}:
 -0.35
 -0.71

In [10]:
Β[1,:,:]

2×2 Matrix{Float64}:
 0.013416  0.0394798
 0.196836  0.398401

In [11]:
0.029 * -0.48 + 0.04 * -0.48

-0.03312

In [12]:
Β[1,:,:] * X[:,1]

UndefVarError: UndefVarError: `X` not defined

In [13]:
X1 = [.9 .75]
Β0 = [0.9 0.6; 0.3 0.5 ]

params = TTVAR_Result([.9 .9; .9 .9], 
    [.001 .001; .001 .001], 
    [.015 .015; .015 .015],
    diagm([.1, .1])
    )

round.(sample(X1, Β0, params, 8)', digits=2)

9×2 Matrix{Float64}:
 0.9    0.75
 0.81   0.69
 0.87   1.08
 0.88   1.15
 0.87   0.52
 0.93   0.71
 0.88  -0.03
 1.04   0.29
 0.06   0.02

In [14]:
#init params
B0 = [0 0; 0 0]
P0 = [0 0; 0 0]
ν = [.011 .007; .009 0.021]
Y = [.035 .04]
X = [.03 .045; .03 0.45]
Σ = diagm([.01, .015])

#predict 
Β1 = B0
P1 = P0 +  ν


F = X * P1 * X' + Σ  #state transision
K = P1 * X' * inv(F) # kalman gain

res = Y .- Β1 * X #residuals

Β_f = B0 + K * res #Beta measurement
P_f = P1 - K * X * P1 #covariance measurmenet

2×2 Matrix{Float64}:
 0.0101843   0.00522623
 0.00675747  0.0160974

In [15]:
#init params
B0 = [0 0; 0 0]
P0 = [0 0; 0 0]
ν = [.011 .007; .009 0.021]
Y = [.035 .04]
X = [.03 .045; .03 0.45]
Σ = diagm([.01, .015])

kalman_step(B0, P0, Y, X, Σ, ν)

2×2 Matrix{Float64}:
 0.011  0.007
 0.009  0.021

In [16]:
X = [0.9 0.75;
0.6 0.55;
0.4 0.78;
0.24 1.0;
0.26 0.81;
0.49 0.61;
0.56 0.01;
0.4 -0.38]

reshape(repeat(X,1,2), (8,2,2))

8×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.9    0.75
 0.6    0.55
 0.4    0.78
 0.24   1.0
 0.26   0.81
 0.49   0.61
 0.56   0.01
 0.4   -0.38

[:, :, 2] =
 0.9    0.75
 0.6    0.55
 0.4    0.78
 0.24   1.0
 0.26   0.81
 0.49   0.61
 0.56   0.01
 0.4   -0.38

In [17]:
X = [0.9 0.75;
0.6 0.55;
0.4 0.78;
0.24 1.0;
0.26 0.81;
0.49 0.61;
0.56 0.01;
0.4 -0.38]

#X = reshape(repeat(X,1,2), (8,2,2))

#= Y = [0.6 0.55;
0.4 0.78;
0.24 1.0;
0.26 0.81;
0.49 0.61;
0.56 0.01;
0.4 -0.38;
0.05 -0.04] =#

Y = [0.6 0.4 0.24 1.0 0.26 0.81 0.49 0.61 0.56 0.01 0.4 -0.38 0.05 -0.04] 

B0 = [0 0; 0 0]
P0 = [0 0; 0 0]
Σ = diagm([.01, .015])
ν = [.015 .025; .015 .035]
res = kalmanFilter(X, Y, B0, P0, Σ, ν)

res[1]

ArgumentError: ArgumentError: indexed assignment with a single value to possibly many locations is not supported; perhaps use broadcasting `.=` instead?

In [18]:
res[2]

0.035

In [19]:
println(res[1][end, :, :])
println(res[2][end, :, :])

MethodError: MethodError: no method matching getindex(::Float64, ::Int64, ::Colon, ::Colon)

Closest candidates are:
  getindex(::Number, ::Integer)
   @ Base number.jl:96
  getindex(::Number, !Matched::Integer...)
   @ Base number.jl:101
  getindex(::Number)
   @ Base number.jl:95
  ...


In [20]:
S_smoothed, P_smoothed = smoother(res[1], res[2])

display(S_smoothed)

display(P_smoothed)


BoundsError: BoundsError: attempt to access Tuple{} at index [1]

In [21]:
display(prepare(X,1)[1])

display(prepare(X,1)[2])


UndefVarError: UndefVarError: `prepare` not defined

In [22]:
Y = [.1 .2]

X = [.15 .18]

C = [.6 .4; .3 .5]

Y .- C * X'

2×2 Matrix{Float64}:
 -0.062  0.038
 -0.035  0.065

In [23]:
C * X'

2×1 Matrix{Float64}:
 0.162
 0.135

In [226]:
#init params
B0 = [0.5, 0.5]
P0 = diagm([.05, .05])
ν = diagm([.011, .007])
Y = .035
X = [0.2, 0.1]'
σ = 0.01


S = measurement_cov(X, P0, σ)
display(S)
K = k_gain(X,ν, S)
display(K)
res = residuals(Y, X, B0)
display(res)
states = update_state(B0, K, res)
display(states)
filtered_cov = update_cov(B0, K, X) 

#[0. 0.] + (K * res)' 


0.0125

2-element Vector{Float64}:
 0.176
 0.05600000000000001

-0.11500000000000002

2-element Vector{Float64}:
 0.47976
 0.49356

2-element Vector{Float64}:
 0.4736
 0.4916

In [227]:
X = [0.2, 0.1]
res = kalman_step2(B0,P0, Y, X, σ, ν)

display(res[1])
display(res[2])

2-element Vector{Float64}:
 0.3921598770176787
 0.44961568024596466

2×2 Matrix{Float64}:
  0.0495596   -0.00534512
 -0.00534512   0.0545027

In [189]:
1 ./ [2.]

1-element Vector{Float64}:
 0.5

In [177]:
X = [1,2]'
b = [2 3; 4 5]

X * b

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 10  13

In [178]:
b

2×2 Matrix{Int64}:
 2  3
 4  5

In [126]:
[1 2] * transpose([1 2])

1×1 Matrix{Int64}:
 5

In [66]:
A = [1, 2]
b = [3]

A .+ b


2-element Vector{Int64}:
 4
 5

In [94]:
[1,2]' * [2,4]

10

In [96]:
[1 2] ⋅ [2 4]

10

albo Matrix 

albo vector z pierwszym transpose 

In [31]:
#= =#

In [32]:
[1 2; 3 4][1,:]

2-element Vector{Int64}:
 1
 2

In [35]:
ν = diagm([.011, .007])

X = [.03 .045]
X * ν

1×2 Matrix{Float64}:
 0.00033  0.000315

In [36]:
ν = [.011, .007]
X = [.03, .045]

X ⋅ ν * transpose(X) .+ σ

1×2 Matrix{Float64}:
 0.0100193  0.010029

In [37]:
tr(transpose([3 3; 4 7]))

10

In [38]:
#obliczyc gdy transpose jest pozniej
X[:,:]' * ν * X[:,:] .+ σ


DimensionMismatch: DimensionMismatch: A has dimensions (1,1) but B has dimensions (2,1)

In [40]:
transpose(X) * ν * X .+ σ

2-element Vector{Float64}:
 0.01001935
 0.010029025

In [41]:
X = [0.9 0.75;
0.6 0.55;
0.4 0.78;
0.24 1.0;
0.26 0.81;
0.49 0.61;
0.56 0.01;
0.4 -0.38]

Y = [0.6 0.4 0.24 1.0 0.26 0.81 0.49 0.61 0.56 0.01 0.4 -0.38 0.05 -0.04] 

kalmanFilter2(X, Y, B0, P0, σ, ν)

DimensionMismatch: DimensionMismatch: tried to assign 2×2 array to 1×2 destination

In [42]:
X[1,:]

2-element Vector{Float64}:
 0.9
 0.75

In [43]:
X = vec(X)
coef = [.011 .007] 
X * coef * vec(X)

DimensionMismatch: DimensionMismatch: second dimension of A, 2, does not match length of x, 16

In [44]:
randn(3,3)

3×3 Matrix{Float64}:
  0.161045  -0.507188    0.944215
 -0.208239  -1.25094     2.41617
  1.35694   -0.00693013  0.420647

In [45]:
diagm([.01])

1×1 Matrix{Float64}:
 0.01

In [46]:
using LinearAlgebra
using Distributions

# Define the dimensions
n = 2  # Number of independent variables
T = 100  # Number of time steps

# Generate synthetic data
X = randn(T, n)
#= true_beta = [0.5 -0.2] .+ 0.1 .* randn(T, n)
y = [X[t, :] * true_beta[t, :] + randn() for t in 1:T] =#

#= 
# Define the state space model parameters
F = I(n)  # State transition matrix (identity matrix)
Q = 0.01 * I(n)  # Process noise covariance
R = 0.1  # Observation noise variance

# Kalman Filter initialization
beta_pred = zeros(n, T)
P_pred = zeros(n, n, T)
beta_filt = zeros(n, T)
P_filt = zeros(n, n, T)

# Initial state
beta_pred[:, 1] = zeros(n)
P_pred[:, :, 1] = I(n)

for t in 1:T
    # Prediction step
    if t > 1
        beta_pred[:, t] = F * beta_filt[:, t-1]
        P_pred[:, :, t] = F * P_filt[:, :, t-1] * F' + Q
    end
    
    # Update step
    K_t = P_pred[:, :, t] * X[t, :]' / (X[t, :] * P_pred[:, :, t] * X[t, :]' + R)
    beta_filt[:, t] = beta_pred[:, t] + K_t * (y[t] - X[t, :] * beta_pred[:, t])
    P_filt[:, :, t] = (I(n) - K_t * X[t, :]) * P_pred[:, :, t]
end

# Print results
println("True coefficients:")
println(true_beta)
println("Filtered coefficients:")
println(beta_filt)
 =#

 F = I(n)  # State transition matrix (identity matrix)
 Q = 0.01 * I(n)  # Process noise covariance
 R = 0.1  # Observation noise variance
 P_pred = zeros(n, n, T)
 P_pred[:, :, 1] = I(n)
 t = 1

# K_t = P_pred[:, :, t] * X[t, :]' / (X[t, :] * P_pred[:, :, t] * X[t, :]' + R)

(X[t, :]' * P_pred[:, :, t] * X[t, :] + R)

2.175607694728655

In [48]:
X = [.03, .045]
C = [.3 .5]
P = diagm([.011, .007])

X * P #* transpose(X)
#dot(C, X)
dot(X, P)

DimensionMismatch: DimensionMismatch: A has dimensions (2,1) but B has dimensions (2,2)

In [49]:
A = [1 2; 3 4]
B = [2, 3]
A * B

2-element Vector{Int64}:
  8
 18

In [50]:
a = [1 2]
b = [2 3]

a * transpose(b)

1×1 Matrix{Int64}:
 8

In [51]:
inv([1 2; 3 4])

2×2 Matrix{Float64}:
 -2.0   1.0
  1.5  -0.5

In [52]:
kron(I(2), X)

4×2 Matrix{Float64}:
 0.03   0.0
 0.045  0.0
 0.0    0.03
 0.0    0.045