In [3]:
import numpy as np
import pandas as pd
from scipy.optimize import minimize, NonlinearConstraint
from scipy.stats import norm

In [4]:
xl = pd.ExcelFile('wartosci_walorow_12_22.xlsx')
sheets = xl.sheet_names

merged = xl.parse(sheets.pop(0))
print(sheets)

for sheet in sheets:
    data = xl.parse(sheet)    
    merged = merged.merge(data, on='Date', how='left') 

xl.close()

assets = merged.columns[1:]
price_changes = merged[assets].pct_change()
price_changes.set_index(merged['Date'], inplace=True)

euro_assets = ['ACWI', 'GovBondG7', 'GlobalCorporate', 'Gold', 'GABHDG', 'EURO_STOXX_Leverage', 'Fallen_Angels']
pln_assets = ['Mwig40tr', 'TBSP', 'EDO']

pln = merged[euro_assets].apply(lambda x: x * merged['EURPLN'])
pln_chng = pln.pct_change()
pln_chng.set_index(merged['Date'], inplace=True)
pln_chng = pd.merge(price_changes[pln_assets], pln_chng, left_index=True, right_index=True)

assets = pln_chng
assets.info()

['MSCI ACWI', 'MWITR', 'TBSP', 'EURPLN', 'Bloomberg Barclays Euro Aggrega', 'EDO', 'Bloomberg Barclays Global Aggre', 'Gold spot price', 'Global aggregate euro hdg', 'EURO STOXX 50 Daily Leverage', 'Bloomberg Barclays Global Corpo']
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 456 entries, 1985-01-01 to 2022-12-01
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Mwig40tr             155 non-null    float64
 1   TBSP                 191 non-null    float64
 2   EDO                  225 non-null    float64
 3   ACWI                 254 non-null    float64
 4   GovBondG7            254 non-null    float64
 5   GlobalCorporate      123 non-null    float64
 6   Gold                 254 non-null    float64
 7   GABHDG               61 non-null     float64
 8   EURO_STOXX_Leverage  252 non-null    float64
 9   Fallen_Angels        78 non-null     float64
dtypes: float64(10)
memory usage: 55.4 KB


In [5]:
def shrinkedCovariance(returns: pd.DataFrame, w: int):
    std = np.diag(returns.std()*np.sqrt(12))
    corr = returns.corr('pearson')
    shrinked_corr = (1-w)*corr + np.ones_like(corr)*w 
    result = std @ shrinked_corr @ std
    return std,corr, shrinked_corr, result

def pstd(cov_matrix, weights):
    return np.sqrt(weights.T @ cov_matrix @ weights)

In [6]:
assets_names = ['TBSP', 'ACWI']

portfolio_returns = assets.iloc[-120:][assets_names]

std, corr, sh_corr, res = shrinkedCovariance(portfolio_returns,0.5)
cov = portfolio_returns.cov()*12

print (portfolio_returns.cov()*12)
print(std)
print(corr)
print(sh_corr)
print(res)
print('---')
print(pstd(cov, np.array([0.4, 0.6])))
print('---')
print(pstd(res, np.array([0.4, 0.6])))




          TBSP      ACWI
TBSP  0.002233 -0.000662
ACWI -0.000662  0.023129
[[0.04725282 0.        ]
 [0.         0.15208061]]
          TBSP      ACWI
TBSP  1.000000 -0.092152
ACWI -0.092152  1.000000
          TBSP      ACWI
TBSP  1.000000  0.453924
ACWI  0.453924  1.000000
          0         1
0  0.002233  0.003262
1  0.003262  0.023129
---
0.09146392619858458
---
0.10123873094081719


In [7]:
ret = assets.iloc[-60:][assets_names]
ret_24 = assets.iloc[-84:-24][assets_names]
ret_48 = assets.iloc[-108:-48][assets_names]
ret_150 = assets.iloc[-150:][assets_names]
print(ret.std()*np.sqrt(12))
print(ret_24.std()*np.sqrt(12))
print(ret_48.std()*np.sqrt(12))
print(ret_150.std()*np.sqrt(12))
print('---')

std, corr, sh_corr, res = shrinkedCovariance(ret,0)
std, corr, sh_corr, res_24 = shrinkedCovariance(ret_24,0)
std, corr, sh_corr, res_48 = shrinkedCovariance(ret_48,0)
std, corr, sh_corr, res_150 = shrinkedCovariance(ret_150,0)


print(pstd(res, np.array([0.4, 0.6])))
print(pstd(res_24, np.array([0.4, 0.6])))
print(pstd(res_48, np.array([0.4, 0.6])))
print(pstd(res_150, np.array([0.4, 0.6])))


print('---')
std, corr, sh_corr, res = shrinkedCovariance(ret,0.75)
std, corr, sh_corr, res_24 = shrinkedCovariance(ret_24,0.75)
std, corr, sh_corr, res_48 = shrinkedCovariance(ret_48,0.75)
std, corr, sh_corr, res_150 = shrinkedCovariance(ret_150,0.75)

print(pstd(res, np.array([0.4, 0.6])))
print(pstd(res_24, np.array([0.4, 0.6])))
print(pstd(res_48, np.array([0.4, 0.6])))
print(pstd(res_150, np.array([0.4, 0.6])))

TBSP    0.058287
ACWI    0.180158
dtype: float64
TBSP    0.019728
ACWI    0.156034
dtype: float64
TBSP    0.024732
ACWI    0.129339
dtype: float64
TBSP    0.044049
ACWI    0.150289
dtype: float64
---
0.10942527346768507
0.09450573239453121
0.07687067421906144
0.08952406152781506
---
0.126273078746576
0.09980622208789802
0.08496410489639229
0.10352840991202439


In [8]:
def get_ef_port_analytically(rets, covm, targ):
    """Solve for the efficient frontier weights for a given expected return
    vector `rets`, covariance matrix `covm`, and expected portfolio return
    `targ`.
    """
    N = rets.shape[0]
    u = np.array([targ, 1])[:, None]
    U = np.vstack([rets, np.ones_like(rets)]).T

    covm_inv = np.linalg.solve(covm, np.eye(N))
    M        = U.T @ covm_inv @ U
    M_inv    = np.linalg.solve(M, np.eye(2))
    weights  = covm_inv @ U @ M_inv @ u

    return weights

In [9]:
def optimize(expectedMean, means: np.array, cov_table: np.array):

    constraint1 = NonlinearConstraint(lambda x : x.sum(),1,1)
    constraint2 = NonlinearConstraint(lambda x: x.dot(means)*12, expectedMean, expectedMean)
    constraint3 = NonlinearConstraint(lambda x: np.all(np.any([x >=0.05, x == 0], axis=0)).astype(int),True,True)
    assets_constraints = [(0.0,1),(0.0,1)]
    obj = lambda x: x.T@cov_table@x
    start = [1/len(means) for n in range(len(means))]
    result = minimize(obj,start,constraints=[constraint1, constraint2],bounds=assets_constraints)
    #result = np.append(result.x, [expectedMean], [result.fun])    

    return np.array(result.x)

In [10]:
print(optimize(0.07,ret.mean()*12,res.cov()*12))
print(optimize(0.06,ret.mean()*12,res.cov()*12))

[0.9503457 0.0496543]
[0.95748907 0.04251093]


In [11]:
ret = assets.iloc[-60:][assets_names]
ret_150 = assets.iloc[-180:][assets_names]

means = ret.mean()*12
#means = np.array([0.035, 0.085])
std, corr, sh_corr, res = shrinkedCovariance(ret,0.5)
print(means)
print(res)
print(pstd(res, np.array([0.5,0.5])))

target = 0.08
av = 10

#1/av * np.linalg.inv(res) @ means
w = get_ef_port_analytically(means, res, target)
#optimize(target, means, res)
print(w)
pstd(res, w)


TBSP    0.000041
ACWI    0.116699
dtype: float64
          0         1
0  0.003397  0.004986
1  0.004986  0.032457
0.10703470394342732
[[0.31458574]
 [0.68541426]]


0
0  0.13317

In [12]:
def get_k_propabilities(probabilites, goal_strategies):
    goals = np.unique(goal_strategies[goal_strategies > 0])
    result = np.zeros(len(goals))
    for k in goals:
        k_index = np.where(goal_strategies == k)
        result[k-1]  = np.take(probabilites, k_index).sum()       
    
    return result


probabilites = np.array([0.1,0.3,0.3, 0.15, 0.1, 0.05])
goal_strategies = np.array([0,0,1,1,2,2])

get_k_propabilities(probabilites, goal_strategies)

#result = [0, 0.45, 0.15]

array([0.45, 0.15])

In [13]:
arr = [[1,2],[3,4]]
np.take(arr,[1], axis=1)

array([[2],
       [4]])

In [14]:
def goal_propability(W, G, t, mu, sig):
    z = (np.log(W)-np.log(G)-(mu-0.5*np.power(sig,2))*t)/(std*np.sqrt(t))
    
    return norm.cdf(-z)
    
def goal_prob2(W, G, t, mu, sig):
    z = ((mu-0.5*np.power(sig,2))*np.sqrt(t) - (1/np.sqrt(t))*np.log(G/W))/sig
    return norm.cdf(z)

W = 90
G = 180
t = 8
mu = 0.08
std = 0.09 #0.1375

print(np.round(goal_propability(W,G, t, mu, std),3))

print(np.round(goal_prob2(W,G, t, mu, std),3))



1.0
0.368


In [86]:
def __prob(W0, W1, mean, std, Infusion, Cost, h):
    return norm.pdf((np.log(W1/(W0+Infusion+Cost))-(mean-0.5*std**2)*h)/(std*np.sqrt(h)))

def calculateTransitionPropabilitiesForAllPorfolios(portfolios,WT,WT1,infusions, h=1):
    l = len(portfolios)
    i = len(WT)
    b = (portfolios[:,0]-0.5*portfolios[:,1]**2)*h
    bi = np.repeat(b, i).reshape(l*i,1)
    c = portfolios[:,1]*np.sqrt(h)
    ci = np.repeat(c, i).reshape(l*i,1)
   
    Wt1 = np.tile(WT1, (l*i,1))
    Wt = np.tile(WT,(l,1)).reshape(i*l,1)+infusions
    result = norm.pdf((np.log(Wt1/Wt)- bi)/ci).reshape(l,i,len(WT1))
    return result/result.sum(2).reshape(l,i,1)

portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057  ], [0.0886, 0.1954]])
WT = np.array([49,50,60,80,100,105])
WT1 = np.array([90,95,100,103,105,110])
VT1 = [0,0,0,100,100,100] 

infusion = 5
h = 1


#goals = [[50, 80], [30, 50],]
VTc0 = np.array([29.014, 29.55, 77.286, 95.997])

#probabilities = calculateTransitionPropabilitiesForAllPorfolios(portfolios,WT,WT1,3)


probabilities = calculateTransitionPropabilitiesForAllPorfolios(portfolios,WT,WT1,infusion,h)

#print(probabilities[2,5,5])
print(__prob(105,WT1,portfolios[2,0],portfolios[2,1],5,0,1))
print(np.round(probabilities,3))




[0.1533746  0.21641459 0.27951946 0.31394848 0.33445915 0.37448256]
[[[1.    0.    0.    0.    0.    0.   ]
  [1.    0.    0.    0.    0.    0.   ]
  [1.    0.    0.    0.    0.    0.   ]
  [0.769 0.221 0.01  0.001 0.    0.   ]
  [0.    0.    0.017 0.105 0.244 0.633]
  [0.    0.    0.001 0.017 0.075 0.908]]

 [[0.91  0.082 0.006 0.001 0.    0.   ]
  [0.901 0.089 0.008 0.002 0.001 0.   ]
  [0.769 0.178 0.035 0.012 0.006 0.001]
  [0.281 0.255 0.18  0.132 0.103 0.049]
  [0.03  0.08  0.158 0.208 0.238 0.286]
  [0.016 0.053 0.131 0.196 0.244 0.36 ]]

 [[0.472 0.243 0.121 0.078 0.058 0.027]
  [0.461 0.244 0.124 0.081 0.061 0.029]
  [0.353 0.237 0.151 0.113 0.092 0.054]
  [0.196 0.192 0.176 0.161 0.151 0.124]
  [0.107 0.141 0.171 0.185 0.193 0.204]
  [0.092 0.129 0.167 0.188 0.2   0.224]]]


-0.77734426

[[ 0.51082562  0.56489285  0.61618614  0.64574494  0.6649763   0.71149632]
 [-0.2006707  -0.14660347 -0.09531018 -0.06575138 -0.04652002  0.        ]
 [ 0.51082562  0.56489285  0.61618614  0.64574494  0.6649763   0.71149632]
 [-0.2006707  -0.14660347 -0.09531018 -0.06575138 -0.04652002  0.        ]
 [ 0.51082562  0.56489285  0.61618614  0.64574494  0.6649763   0.71149632]
 [-0.2006707  -0.14660347 -0.09531018 -0.06575138 -0.04652002  0.        ]]