In [90]:
%load_ext autoreload
%autoreload 2

from model.grid import generateGrid
from model._utilities import Goals
from model.investment_planner import InvestmentPlanner, calculateBelman
from model.propabilities import calculateTransitionPropabilitiesForAllPorfolios, calculateTransitionPropabilitiesForGoals
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [70]:
portfolios = np.array([[0.05258386, 0.03704926],
       [0.05515672, 0.03960988],
       [0.05772681, 0.04625568],
       [0.06029967, 0.05555016],
       [0.06286483, 0.06637403],
       [0.06545148, 0.07813246],
       [0.06801664, 0.09041086],
       [0.07059443, 0.103057  ],
       [0.07315959, 0.11592848],
       [0.07573245, 0.12898073],
       [0.07830254, 0.14213997],
       [0.0808754 , 0.15540374],
       [0.08344549, 0.16872224],
       [0.08601835, 0.18210899],
       [0.08858351, 0.19552512]])

In [77]:
W0 = 100
imax = 10  

#infusions = np.zeros(T)

goals = Goals([{
        "time": 2,
        "cost": 107,
        "utility": 100                
    }])

infusions = np.full(goals.get_investment_period(),0)

grid = generateGrid(W0, imax, infusions, goals, portfolios[0,0], portfolios[0,1], portfolios[-1,0], portfolios[-1,1])
np.round(grid,2)
#np.savetxt('grid.txt', grid, delimiter=', ', fmt='%10.2f')

array([[100.  , 100.  , 100.  , 100.  , 100.  , 100.  , 100.  , 100.  ,
        100.  , 100.  ],
       [ 50.56,  57.95,  66.42,  76.12,  87.25, 100.  , 114.61, 131.36,
        150.56, 172.56],
       [  0.68,   1.27,   2.37,   4.43,   8.26,  15.41,  28.74,  53.61,
        100.  , 186.52],
       [ 37.69,  48.11,  61.4 ,  78.36, 100.  , 127.62, 162.88, 207.87,
        265.29, 338.58]])

In [105]:
portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057  ], [0.0886, 0.1954]])
WT = np.array([0.68, 1.27, 2.37, 4.43, 8.26, 15.41, 28.74, 53.61, 100., 141, 186.52])
WT1= np.array([37.69, 48.11, 61.4 , 78.36, 100., 127.62, 162.88, 207.87, 265.29, 180, 338.58])

np.round(calculateTransitionPropabilitiesForAllPorfolios(portfolios,WT,WT1, 0), 3)

#TODO zrobić kolejne kroki belmann equtation



array([[[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.001, 0.999, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   , 0.006, 0.994, 0.   , 0.   ,
         0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0. 

In [107]:
goals = np.array([[120,150]])
goal_utilities = goals[:,1]
np.vstack(([0],np.expand_dims(goal_utilities,1)))

array([[  0],
       [150]])

In [106]:

goal_strategies, portfolios_strategies, probabilities = calculateBelman(grid,goals,portfolios)





ValueError: could not broadcast input array from shape (9,) into shape (10,)