In [186]:
%load_ext autoreload
%autoreload 2

import numpy as np
from investment_planner import calculateTransitionPropabilitiesForAllPorfolios, generateGrid, calculateTransitionPropabilities, get_portfolios_strategies, calculateValuesForLastPeriod, get_goals_strategies, __get_value_index
from scipy.stats import norm

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [172]:

portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057  ], [0.0886, 0.1954]])
W0 = np.array([90,95,100,105])
W1 = np.array([100,103,105,110])
infusions = 2
cost = 3
h = 1

values = [0,0,100,100]

#propabilities = calculateTransitionPropabilitiesForAllPorfolios(portfolios, W0, W1, infusions, cost, h)
propabilities = np.array([[[0.451, 0.334, 0.197, 0.018],
                                    [0.271, 0.27,  0.258, 0.2  ],
                                    [0.255, 0.256, 0.253, 0.237]],

                                    [[0.14,  0.307, 0.366, 0.187],
                                    [0.221, 0.254, 0.266, 0.259],
                                    [0.24,  0.251, 0.255, 0.254]],

                                    [[0.017, 0.105, 0.244, 0.634],
                                    [0.177, 0.234, 0.268, 0.322],
                                    [0.227, 0.246, 0.256, 0.271]],

                                    [[0.001, 0.017, 0.075, 0.908],
                                    [0.14,  0.211, 0.262, 0.387],
                                    [0.215, 0.241, 0.257, 0.288]]])
print(np.round(propabilities, 3))
values = propabilities*values
np.round(np.amax(values.sum(2),1),3)
#values.sum(2)


[[[0.451 0.334 0.197 0.018]
  [0.271 0.27  0.258 0.2  ]
  [0.255 0.256 0.253 0.237]]

 [[0.14  0.307 0.366 0.187]
  [0.221 0.254 0.266 0.259]
  [0.24  0.251 0.255 0.254]]

 [[0.017 0.105 0.244 0.634]
  [0.177 0.234 0.268 0.322]
  [0.227 0.246 0.256 0.271]]

 [[0.001 0.017 0.075 0.908]
  [0.14  0.211 0.262 0.387]
  [0.215 0.241 0.257 0.288]]]


array([49. , 55.3, 87.8, 98.3])

In [173]:
portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057], [0.0886, 0.1954]])
W0 = 100
T = 12
#infusions = [0,25000,25000,25000,25000,25000,25000,25000,25000,25000,25000]
infusions = np.zeros(13)
goals = [0,0,0,0,0,0,0,100,0,0,0,0,150]
iMax = 281

grid = generateGrid(W0,T,iMax, infusions, goals, portfolios[0,0], portfolios[0,1], portfolios[2,0], portfolios[2,1])
grid = grid.T

In [174]:
W0 = 100
meanMax = 0.0886
stdMin = 0.0374
stdMax = 0.1954
t =11

W0*np.exp((meanMax-(stdMin**2/2))*t + 3*stdMax*np.sqrt(t))

1837.723

In [175]:
k = np.array([[105,100],[110,200]])
wealthInT = np.array([90,95,100,105,110])
Wk = np.tile(wealthInT, (2,1))
ki = np.tile(k, (2, 5,1))
#np.where(Wk >= k[:,0], k[:,1], 0)
ki

array([[[105, 100],
        [110, 200],
        [105, 100],
        [110, 200],
        [105, 100],
        [110, 200],
        [105, 100],
        [110, 200],
        [105, 100],
        [110, 200]],

       [[105, 100],
        [110, 200],
        [105, 100],
        [110, 200],
        [105, 100],
        [110, 200],
        [105, 100],
        [110, 200],
        [105, 100],
        [110, 200]]])

In [176]:
WT1 = np.array([90,95,100,105,110])
WT1P = WT1 * [0.2,0.35, 0.2 ,0.15,0.1]
WT1P.reshape((5,1))

array([[18.  ],
       [33.25],
       [20.  ],
       [15.75],
       [11.  ]])

In [177]:
arr = np.array([[1,2,3,4],[1,2,3]])
arr2 = np.array([1,2])
result = arr*arr2
result

C:\Users\matsz\AppData\Local\Temp\ipykernel_28528\4293703242.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4],[1,2,3]])


array([list([1, 2, 3, 4]), list([1, 2, 3, 1, 2, 3])], dtype=object)

In [178]:
def get_ef_port_analytically(rets, covm, targ):
    """Solve for the efficient frontier weights for a given expected return
    vector `rets`, covariance matrix `covm`, and expected portfolio return
    `targ`.
    """
    N = rets.shape[0]
    u = np.array([targ, 1])[:, None]
    U = np.vstack([rets, np.ones_like(rets)]).T

    covm_inv = np.linalg.solve(covm, np.eye(N))
    M        = U.T @ covm_inv @ U
    M_inv    = np.linalg.solve(M, np.eye(2))
    weights  = covm_inv @ U @ M_inv @ u

    return weights


In [179]:
cov_tab = np.array([[0.0002, -0.00],
                    [-0.00, 0.0013]])
means = np.array([0.0307, 0.1094])

mu = 0.0744
std = 0.0712

w = get_ef_port_analytically(means,cov_tab,mu)

w

array([[0.44472681],
       [0.55527319]])

In [180]:
arr = np.empty((3,3))

arr[:] = np.nan
arr




array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [181]:
mean = 0.0886
std = 0.1954
W0 = 105
W1 = np.array([105,110,115])
h= 1
np.round(norm.pdf((np.log(W1/(W0))-(mean-0.5*std**2)*h)/(std*np.sqrt(h))),3)

#100 [0.39670583, 0.39547966, 0.37397359]
#105 [0.37448256, 0.39619069, 0.39654302]


array([0.374, 0.396, 0.397])

In [182]:
portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057  ], [0.0886, 0.1954]])
W0 = np.array([90,95,100,105])
W1 = np.array([100,103,105,110])
infusions = 2
cost = 50
h = 1

values = [0,0,100,100]

propabilities = calculateTransitionPropabilitiesForAllPorfolios(portfolios, W0, W1, infusions, cost, h)
''' propabilities = np.array([[[0.451, 0.334, 0.197, 0.018],
                                    [0.271, 0.27,  0.258, 0.2  ],
                                    [0.255, 0.256, 0.253, 0.237]],

                                    [[0.14,  0.307, 0.366, 0.187],
                                    [0.221, 0.254, 0.266, 0.259],
                                    [0.24,  0.251, 0.255, 0.254]],

                                    [[0.017, 0.105, 0.244, 0.634],
                                    [0.177, 0.234, 0.268, 0.322],
                                    [0.227, 0.246, 0.256, 0.271]],

                                    [[0.001, 0.017, 0.075, 0.908],
                                    [0.14,  0.211, 0.262, 0.387],
                                    [0.215, 0.241, 0.257, 0.288]]]) '''
print(np.round(propabilities, 3))
values = propabilities*values
np.round(np.amax(values.sum(2),1),3)

[[[1.    0.    0.    0.   ]
  [0.888 0.091 0.02  0.   ]
  [0.499 0.266 0.174 0.06 ]]

 [[1.    0.    0.    0.   ]
  [0.848 0.119 0.032 0.001]
  [0.466 0.271 0.188 0.075]]

 [[1.    0.    0.    0.   ]
  [0.8   0.149 0.048 0.003]
  [0.436 0.274 0.2   0.09 ]]

 [[1.    0.    0.    0.   ]
  [0.747 0.18  0.068 0.006]
  [0.408 0.275 0.211 0.106]]]


array([23.493, 26.289, 29.014, 31.661])

In [183]:
def __get_value_index(WT, wealth_value):
    difference = np.absolute(WT - wealth_value)
    index = np.argmin(difference)
    return index



In [213]:
portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057  ], [0.0886, 0.1954]])
WT = np.array([49,50,60,80,100,105])
WT1 = [90,95,100,103,105,110]
VT1 = [0,0,0,100,100,100]
c = 50
#goals = [[50, 80], [30, 50],]
VTc0 = np.array([29.014, 29.55, 77.286, 95.997])

probabilities = calculateTransitionPropabilitiesForAllPorfolios(portfolios,WT,WT1,3,0)

portfolios_strategies, VT, chosen_propabilities = get_portfolios_strategies(VT1,probabilities)
print(portfolios_strategies)
print(VT)
print(np.round(chosen_propabilities,3))
chosen_propabilities.shape

[2 2 2 2 0 0]
[14.79437951 15.58145938 24.11574646 41.94244819 95.45553882 99.66923255]
[[[0.496 0.242 0.114 0.072 0.    0.   ]]

 [[0.484 0.243 0.118 0.075 0.    0.   ]]

 [[0.373 0.239 0.146 0.107 0.    0.   ]]

 [[0.208 0.197 0.175 0.158 0.    0.   ]]

 [[0.113 0.146 0.172 0.184 0.326 0.446]]

 [[0.097 0.134 0.169 0.187 0.126 0.834]]]


(6, 1, 6)

In [238]:
%precision 3


goals = np.array([[40,10],[49, 15],[60, 30]])
infusion = 3

VTc0 = np.array([14.794, 15.581, 24.116, 41.942, 95.456, 99.669])

Wt = WT

goal_strategies, portfolio_strategies, values, probabilities = get_goals_strategies(goals, infusion, WT,WT1, VT1, portfolios)


print(goal_strategies)
print(portfolio_strategies)
print(np.round(values,3))
print(np.round(probabilities,3))


[1 2 2 3 0 0]
[2 2 2 2 0 0]
[22.532 28.269 36.457 69.379 95.456 99.669]
[[0.484 0.239 0.146 0.158 0.    0.   ]
 [0.52  0.242 0.139 0.152 0.044 0.019]
 [0.52  0.242 0.139 0.152 0.    0.   ]
 [0.    0.    0.    0.152 0.    0.   ]]


```
expected values array([24.794, 29.794, 29.794, 44.794, 95.456, 99.669])
array([[14.794, 15.581, 24.116, 41.942, 95.456, 99.669],
       [24.794, 24.794, 24.794, 24.794, 34.116, 34.116],
       [14.794, 29.794, 29.794, 29.794, 30.581, 39.116],
       [14.794, 15.581, 24.116, 44.794, 44.794, 44.794]])

```

## TODO
- sprawdzić wrażliwość na rożne inputy
- W0 jest większe niż cele

In [246]:
from investment_planner import InvestmentPlanner 

investment_planner = InvestmentPlanner()

goals = np.array([[[0,0]],[[0,0]],[[0,0]],[[0,0]],[[0,0]],[[90,60]],[[0,0]],[[0,0]],[[0,0]],[[0,0]],[[120,100]]])
portfolios = np.array([[0.0526, 0.0374], [0.07059443, 0.103057  ], [0.0886, 0.1954]])
investment_planner.set_params(10, 100, 10, 1, goals, portfolios)

glide_path = investment_planner.glide_paths
wealth_grid = investment_planner.grid
probabilitiesT = investment_planner.probabilitiesT
goal_strategies = investment_planner._goal_strategies

#TODO refactor investment planner - chosen propabilieis to get portfolio_propabilities


In [ ]:
WTt = np.repeat(10,1200)
goals = np.array([[40,10],[49, 15],[60, 30]])

In [ ]:
np.tile(WTt,(3,1)) - np.repeat(goals[:,0],1200).reshape((3,1200))



array([[-30, -30, -30, ..., -30, -30, -30],
       [-39, -39, -39, ..., -39, -39, -39],
       [-50, -50, -50, ..., -50, -50, -50]])

1: 48.057
2. 64.226
m. 56.305

In [231]:
arr = np.array([[1,2],[3,4]])
take = np.array([[1]])
chosen = np.take_along_axis(arr, take,axis=1)
np.squeeze(chosen)

array([2, 4])