In [234]:
from scipy.stats import multivariate_normal
import numpy as np

%load_ext autoreload
%autoreload 2

In [45]:
scenario_count = 1
t = 5
returns = np.zeros((scenario_count,t,2))
means = np.array([0.035, 0.085])
cov = np.array([[0.05,0.04],
                [0.04, 0.11]])

for i in range(0,scenario_count):
    returns[i] = multivariate_normal.rvs(means,cov=cov, size=t)

#prices = returns + np.ones_like(returns)
#prices = np.cumprod(prices,axis=0)
#prices = prices * np.[10,5]
#prices
returns

array([[[-0.08004581,  0.03487759],
        [ 0.18726262,  0.29438996],
        [ 0.43617395,  0.05512082],
        [-0.14975919, -0.18283747],
        [-0.2819594 , -0.39066   ]]])

In [53]:
prices = np.array([
32.7,
25.18,
23.67,
31.48,
36.20
])
returns = prices.reshape((5,1))
returns

array([[32.7 ],
       [25.18],
       [23.67],
       [31.48],
       [36.2 ]])

In [69]:
400 / 55.88

7.158196134574087

In [78]:
prices= np.array([[[32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[28.2, 52.00],
                        [26.4, 47.84],
                        [25.8, 51.67],
                        [32.1, 54.25],
                        [36.6, 55.88]]])

inflows = np.array([0,1000,1000,1000,1000])
weights = np.array([0.6,0.4])

shares = np.zeros((len(inflows),2,2))

for t in range (len(inflows)):
    shares[t] = (inflows[t]*weights) / prices[:,t]

shares.sum(0)
    


array([[86.3736379 , 27.81133275],
       [81.06811809, 30.63410807]])

In [90]:
from dataclasses import dataclass


@dataclass
class Spike:
    rank: int = 1

Spike(3).rank



3

In [113]:
@dataclass
class Transaction:
    delta_shares: np.array
    outflows: int = 0

assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
shares_owned = np.array([[285, 107],[292, 109]])
inflow = 0
goal = (13000,0.8)

cashflow = inflow - goal[0]
current_value = np.sum(shares_owned * prices, 1) 
      
delta_shares = np.where(np.abs(cashflow) <= current_value, np.fix((cashflow*assets_weights) / prices), -shares_owned)
outflows = np.abs(np.sum(delta_shares * prices,axis=1))

print(shares_owned)

max_outflow_value = current_value * goal[1]
np.fix(shares_owned * goal[1])



[[285 107]
 [292 109]]


array([[228.,  85.],
       [233.,  87.]])

In [134]:
goal = (14000,1)
assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
#shares_owned = np.array([[282, 99],[290, 91]])
shares_owned = np.array([[0, 0],[0, 0]])
inflow = 10000

In [136]:
goal_target = goal[0] 
goal_max_outflow_percent = goal[1]
current_assets_value = shares_owned * prices
current_value = np.sum(current_assets_value, 1) 
expected_value = current_value + inflow - goal_target
#max_outflow_value = current_value * goal_max_outflow_percent
    
delta_value = expected_value.reshape((2,1)) * assets_weights - current_assets_value
    
#delta_shares = - np.fix(delta_value / prices)
delta_shares = - delta_value / prices

#outflows = np.round(np.abs(np.sum(delta_shares * prices,axis=1)),2)

#print(outflows)    
#Transaction(delta_shares, outflows)
print(expected_value)
print(assets_weights)
delta_shares



[-4000. -4000.]
[0.6 0.4]


array([[70.1754386 , 26.85915729],
       [76.38446849, 28.63278454]])

In [149]:
shares_owned = np.array([[25,15],[24,17]])
delta = np.array([[5,5],[4,7]])
shares_owned += delta
np.sum(shares_owned * prices[:,1],1)

array([2011. , 2037.6])

In [29]:
class PorfoliosSumulator:
    def __init__(self) -> None:
        pass

assets_weights = np.array([0.4,0.6])
shares = np.zeros((scenario_count,t,assets_weights.shape[0]))
initial_wealth =100

#shares[0] = 

initial_wealth *assets_weights


array([40., 60.])

Portfolio class:
- [ ] get withrowals for
    - no goal
    - single goal
    - multiple goals in different times    
    - dla emerytury - coroczne dla kilku celow
- add infusions
- rebalance
- include costs



In [150]:
import tensorflow as tf

In [168]:
weights = tf.Variable([0.3,0.4,0.3])
returns = tf.constant([0.035, 0.085, 0.06])

def loss(weights, returns):
    return tf.tensordot(weights,returns,axes=1)

y = loss(weights, returns)

with tf.GradientTape() as type:
    y = loss(weights, returns)

weights.assign([0.5,0.3,0.2])

type.gradient(y, [weights, returns])



[<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.035, 0.085, 0.06 ], dtype=float32)>,
 None]

In [187]:
x = tf.Variable(8.0)
y = tf.Variable(4.0)

@tf.function
def mypower(x,y):
    t = tf.Variable(0.0)
    for i in range(4):
        t.assign_add(x + y)
    return t 

with tf.GradientTape() as tape:
    tape.watch(x)
    tape.watch(y)
    z = mypower(x,y)

print(tape.gradient(z, [x,y]))

mypower(x,y)

ValueError: in user code:

    File "C:\Users\matsz\AppData\Local\Temp\ipykernel_33444\49569053.py", line 6, in mypower  *
        t = tf.Variable(0.0)

    ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function. See https://www.tensorflow.org/guide/function#creating_tfvariables for more information.


In [230]:
arr = np.array([[[30.00, 50.00],       
                        [32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[30.0,	50.0],
                         [28.2,	52.00],
                         [24.82, 47.84],
                         [24.07, 51.67],
                         [25.76, 54.25],
                         [31.42, 55.88]]])
T = len(arr[:,0:3])
arr[:,0:3]
arr[:,-1].shape

(2, 2)

In [240]:
from sb_gbi.portfolio_simulator import PortfoliosSimulator

inflows = np.array([10000,1000,1000,1000,1000,0])
  

goals = {
        5: (16000,1)
    }  

expected_final_value = np.array([873.39, 0])
expectet_outflows = np.array([[16000.00, 15398.00]])

portfolios_simulator = PortfoliosSimulator()
    
portfolios_simulator.set_params(
        assets_prices=prices,        
        assets_weights=np.array([0.6,0.4]),       
        inflows = inflows,
        goals = goals
        )


portfolios_simulator.get_shares()

IndexError: tuple index out of range

In [228]:
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
shares_owned = np.array([[288, 101],[291, 92]])
np.sum(prices * shares_owned,1)
#9143.22 + 5140.96
14284.18


array([15866.17, 14284.18])