In [2]:
from scipy.stats import multivariate_normal
import numpy as np

In [45]:
scenario_count = 1
t = 5
returns = np.zeros((scenario_count,t,2))
means = np.array([0.035, 0.085])
cov = np.array([[0.05,0.04],
                [0.04, 0.11]])

for i in range(0,scenario_count):
    returns[i] = multivariate_normal.rvs(means,cov=cov, size=t)

#prices = returns + np.ones_like(returns)
#prices = np.cumprod(prices,axis=0)
#prices = prices * np.[10,5]
#prices
returns

array([[[-0.08004581,  0.03487759],
        [ 0.18726262,  0.29438996],
        [ 0.43617395,  0.05512082],
        [-0.14975919, -0.18283747],
        [-0.2819594 , -0.39066   ]]])

In [53]:
prices = np.array([
32.7,
25.18,
23.67,
31.48,
36.20
])
returns = prices.reshape((5,1))
returns

array([[32.7 ],
       [25.18],
       [23.67],
       [31.48],
       [36.2 ]])

In [69]:
400 / 55.88

7.158196134574087

In [78]:
prices= np.array([[[32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[28.2, 52.00],
                        [26.4, 47.84],
                        [25.8, 51.67],
                        [32.1, 54.25],
                        [36.6, 55.88]]])

inflows = np.array([0,1000,1000,1000,1000])
weights = np.array([0.6,0.4])

shares = np.zeros((len(inflows),2,2))

for t in range (len(inflows)):
    shares[t] = (inflows[t]*weights) / prices[:,t]

shares.sum(0)
    


array([[86.3736379 , 27.81133275],
       [81.06811809, 30.63410807]])

In [90]:
from dataclasses import dataclass


@dataclass
class Spike:
    rank: int = 1

Spike(3).rank



3

In [113]:
@dataclass
class Transaction:
    delta_shares: np.array
    outflows: int = 0

assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
shares_owned = np.array([[285, 107],[292, 109]])
inflow = 0
goal = (13000,0.8)

cashflow = inflow - goal[0]
current_value = np.sum(shares_owned * prices, 1) 
      
delta_shares = np.where(np.abs(cashflow) <= current_value, np.fix((cashflow*assets_weights) / prices), -shares_owned)
outflows = np.abs(np.sum(delta_shares * prices,axis=1))

print(shares_owned)

max_outflow_value = current_value * goal[1]
np.fix(shares_owned * goal[1])



[[285 107]
 [292 109]]


array([[228.,  85.],
       [233.,  87.]])

In [108]:

def transactions(inflow, shares_owned, assets_weights, prices, goal = 0):
    
    goal_target = goal[0] 
    goal_max_outflow_percent = goal[1]
    cashflow = inflow - goal_target
    current_value = np.sum(shares_owned * prices, 1) 
    max_outflow_value = current_value * goal_max_outflow_percent
      
    delta_shares = np.where(np.abs(cashflow) <= max_outflow_value, np.fix((cashflow*assets_weights) / prices), -np.fix(shares_owned * goal_max_outflow_percent))
    outflows = np.round(np.abs(np.sum(delta_shares * prices,axis=1)),2)
    
    return Transaction(delta_shares, outflows)

transactions(inflow,shares_owned,assets_weights,prices,goal)

Transaction(delta_shares=array([[-228.,  -85.],
       [-233.,  -87.]]), outflows=array([12861.05, 12182.42]))

In [29]:
class PorfoliosSumulator:
    def __init__(self) -> None:
        pass

assets_weights = np.array([0.4,0.6])
shares = np.zeros((scenario_count,t,assets_weights.shape[0]))
initial_wealth =100

#shares[0] = 

initial_wealth *assets_weights


array([40., 60.])

Portfolio class:
- [ ] get withrowals for
    - no goal
    - single goal
    - multiple goals in different times    
    - dla emerytury - coroczne dla kilku celow
- add infusions
- rebalance
- include costs

