In [120]:
from scipy.stats import multivariate_normal
import numpy as np
import tensorflow as tf

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [121]:
scenario_count = 1
t = 5
returns = np.zeros((scenario_count,t,2))
means = np.array([0.035, 0.085])
cov = np.array([[0.05,0.04],
                [0.04, 0.11]])

for i in range(0,scenario_count):
    returns[i] = multivariate_normal.rvs(means,cov=cov, size=t)

#prices = returns + np.ones_like(returns)
#prices = np.cumprod(prices,axis=0)
#prices = prices * np.[10,5]
#prices
returns

array([[[-0.30923623, -0.12396889],
        [-0.09091859, -0.72404968],
        [ 0.16654057,  0.01827234],
        [ 0.01959816,  0.39269803],
        [-0.2730689 , -0.34866914]]])

In [122]:
prices = np.array([
32.7,
25.18,
23.67,
31.48,
36.20
])
returns = prices.reshape((5,1))
returns

array([[32.7 ],
       [25.18],
       [23.67],
       [31.48],
       [36.2 ]])

In [123]:
400 / 55.88

7.158196134574087

In [124]:
prices= np.array([[[32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[28.2, 52.00],
                        [26.4, 47.84],
                        [25.8, 51.67],
                        [32.1, 54.25],
                        [36.6, 55.88]]])

inflows = np.array([0,1000,1000,1000,1000])
weights = np.array([0.6,0.4])

shares = np.zeros((len(inflows),2,2))

for t in range (len(inflows)):
    shares[t] = (inflows[t]*weights) / prices[:,t]

shares.sum(0)
    


array([[86.3736379 , 27.81133275],
       [81.06811809, 30.63410807]])

In [125]:
from dataclasses import dataclass


@dataclass
class Spike:
    rank: int = 1

Spike(3).rank



3

In [126]:
@dataclass
class Transaction:
    delta_shares: np.array
    outflows: int = 0

assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
shares_owned = np.array([[285, 107],[292, 109]])
inflow = 0
goal = (13000,0.8)

cashflow = inflow - goal[0]
current_value = np.sum(shares_owned * prices, 1) 
      
delta_shares = np.where(np.abs(cashflow) <= current_value, np.fix((cashflow*assets_weights) / prices), -shares_owned)
outflows = np.abs(np.sum(delta_shares * prices,axis=1))

print(shares_owned)

max_outflow_value = current_value * goal[1]
np.fix(shares_owned * goal[1])



[[285 107]
 [292 109]]


array([[228.,  85.],
       [233.,  87.]])

In [127]:
goal = (14000,1)
assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
#shares_owned = np.array([[282, 99],[290, 91]])
shares_owned = np.array([[0, 0],[0, 0]])
inflow = 10000

In [128]:
goal_target = goal[0] 
goal_max_outflow_percent = goal[1]
current_assets_value = shares_owned * prices
current_value = np.sum(current_assets_value, 1) 
expected_value = current_value + inflow - goal_target
#max_outflow_value = current_value * goal_max_outflow_percent
    
delta_value = expected_value.reshape((2,1)) * assets_weights - current_assets_value
    
#delta_shares = - np.fix(delta_value / prices)
delta_shares = - delta_value / prices

#outflows = np.round(np.abs(np.sum(delta_shares * prices,axis=1)),2)

#print(outflows)    
#Transaction(delta_shares, outflows)
print(expected_value)
print(assets_weights)
delta_shares



[-4000. -4000.]
[0.6 0.4]


array([[70.1754386 , 26.85915729],
       [76.38446849, 28.63278454]])

In [129]:
shares_owned = np.array([[25,15],[24,17]])
delta = np.array([[5,5],[4,7]])
shares_owned += delta
np.sum(shares_owned * prices[:,1],1)

array([2904.7 , 3009.08])

In [130]:
class PorfoliosSumulator:
    def __init__(self) -> None:
        pass

assets_weights = np.array([0.4,0.6])
shares = np.zeros((scenario_count,t,assets_weights.shape[0]))
initial_wealth =100

#shares[0] = 

initial_wealth *assets_weights


array([40., 60.])

Portfolio class:
- [ ] get withrowals for
    - no goal
    - single goal
    - multiple goals in different times    
    - dla emerytury - coroczne dla kilku celow
- add infusions
- rebalance
- include costs



In [131]:
import tensorflow as tf

In [132]:
weights = tf.Variable([0.3,0.4,0.3])
returns = tf.constant([0.035, 0.085, 0.06])

def loss(weights, returns):
    return tf.tensordot(weights,returns,axes=1)

y = loss(weights, returns)

with tf.GradientTape() as type:
    y = loss(weights, returns)

weights.assign([0.5,0.3,0.2])

type.gradient(y, [weights, returns])



[<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.035, 0.085, 0.06 ], dtype=float32)>,
 None]

In [133]:
arr = np.array([[[30.00, 50.00],       
                        [32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[30.0,	50.0],
                         [28.2,	52.00],
                         [24.82, 47.84],
                         [24.07, 51.67],
                         [25.76, 54.25],
                         [31.42, 55.88]]])
arr.shape

(2, 6, 2)

In [137]:
means = [0.03, 0.05, 0.06, 0.09]
cov = [[0.02, -0.00, -0.00, -0.00],[0.00, 0.04, 0.03, 0.04],[-0.00, 0.03, 0.20, -0.00], [-0.00,0.04, -0.00, 0.13]]      

number_of_scenarios = 600
T = 121
prices = []         

for i in range (number_of_scenarios):
    returns = multivariate_normal.rvs(means,cov, T) + 1
    prices.append(np.cumprod(returns,axis=0)*100)
    #prices.append(returns)

prices = np.absolute(prices)
np.round(prices,2)

prices.shape

            

(600, 121, 4)

In [146]:
from sb_gbi.tf.porfolios_simulator_tf import PortfoliosSimulator
%reload_ext autoreload
%autoreload 2

inflows = np.full(T, 1000.0)
inflows[0] = 10000.0
prices = tf.constant(np.round(prices,2), dtype=tf.float32)

#assets_weights = np.full((T,4),[0.25,0.25, 0.25, 0.25])
assets_weights = tf.Variable(tf.fill((T,4),0.25))

goals = {
        120: (240000.0,1.0)
    }  


portfolios_simulator = PortfoliosSimulator()



<tf.Tensor: shape=(600, 121, 4), dtype=float32, numpy=
array([[[1.0413000e+02, 8.8419998e+01, 6.7900002e+01, 8.0800003e+01],
        [1.0923000e+02, 1.3114000e+02, 1.4261000e+02, 1.5532001e+02],
        [7.8370003e+01, 1.0760000e+02, 1.9350000e+02, 6.9550003e+01],
        ...,
        [2.2861201e+03, 2.9873999e+02, 0.0000000e+00, 6.3049999e+01],
        [2.5875901e+03, 2.7731000e+02, 0.0000000e+00, 7.3279999e+01],
        [3.2558799e+03, 2.6398999e+02, 0.0000000e+00, 5.0380001e+01]],

       [[1.3389000e+02, 1.3350000e+02, 5.3080002e+01, 1.7348000e+02],
        [1.4439999e+02, 1.5888000e+02, 7.7830002e+01, 2.2782001e+02],
        [1.2782000e+02, 1.9970000e+02, 1.0106000e+02, 2.9879001e+02],
        ...,
        [1.3655000e+02, 5.5691998e+02, 0.0000000e+00, 1.1652513e+05],
        [1.7305000e+02, 4.9834000e+02, 0.0000000e+00, 8.8875094e+04],
        [1.5719000e+02, 7.0419000e+02, 0.0000000e+00, 8.4603367e+04]],

       [[8.4519997e+01, 8.7300003e+01, 1.5627000e+02, 6.3520000e+01],
     

In [144]:
portfolios_simulator.set_params(
        assets_prices=prices,        
        assets_weights= assets_weights,       
        inflows = inflows,
        goals = goals
        )

for i in range(100):
        portfolios_simulator.set_params(
        assets_prices=prices,        
        assets_weights= assets_weights,       
        inflows = inflows,
        goals = goals
        )
        outflows = portfolios_simulator()

outflows

TypeError: in user code:

    File "c:\Users\matsz\programowanie\Optymalizacja portfela\sb_gbi\tf\porfolios_simulator_tf.py", line 18, in transaction  *
        current_assets_value = tf.multiply(shares_owned, prices)

    TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float64 of argument 'x'.


In [ ]:
with tf.GradientTape() as tape:
    tape.watch(assets_weights)
    portfolios_simulator.run()
    probs = portfolios_simulator.get_goals_achevement_probabilities()

print(tape.gradient(probs, assets_weights))

None


In [ ]:
prices = np.array([[[30.00, 50.00],       
                        [32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[30.0,	50.0],
                         [28.2,	52.00],
                         [24.82, 47.84],
                         [24.07, 51.67],
                         [25.76, 54.25],
                         [31.42, 55.88]]])

shares = [[10,4],[0,0]]

np.sum(shares * prices[:,-1])

580.28

In [ ]:
def calculate_prob_of_goal_achivement(goals_targets: np.ndarray, goals_outflows: np.ndarray):
    number_of_scenarios = goals_outflows.shape[1]
    total_goals_outflows = np.sum(goals_outflows, axis=1)
    probabilities = total_goals_outflows / np.multiply(goals_targets, number_of_scenarios)
    return probabilities

goal_outflows0 = np.asarray([[0,0],[0,0]])
goal_outflows1 = np.array([[8000, 8000, 8000], [6000, 5775.12, 6000], [6000,6000,6000], [0,0,0]])
goal_target = [8000,6000, 12000, 4000]

calculate_prob_of_goal_achivement(goal_target, goal_outflows1)

calculate_prob_of_goal_achivement([8000,6000], np.array([[8000, 8000], [6000, 5775.12]]))

array([1.     , 0.98126])

In [ ]:
goals = {3: (8000,1), 5: (6000,1)}

list(map(lambda x: x[0],  list(goals.values())))

[8000, 6000]

trainable_variables: assets_weights, max_goal_withroval

non_trainable_variables: prices, inflows, goals_target, goals_utilities

output: utilitiy_function (probs * goal_utilities)

secondary_outputs: portfolio irr, portfolio_final_value 

requiremnts:
porfolios_simulator() -> probs


