In [1]:
from scipy.stats import multivariate_normal
import numpy as np
import tensorflow as tf

%load_ext autoreload
%autoreload 2

In [121]:
scenario_count = 1
t = 5
returns = np.zeros((scenario_count,t,2))
means = np.array([0.035, 0.085])
cov = np.array([[0.05,0.04],
                [0.04, 0.11]])

for i in range(0,scenario_count):
    returns[i] = multivariate_normal.rvs(means,cov=cov, size=t)

#prices = returns + np.ones_like(returns)
#prices = np.cumprod(prices,axis=0)
#prices = prices * np.[10,5]
#prices
returns

array([[[-0.30923623, -0.12396889],
        [-0.09091859, -0.72404968],
        [ 0.16654057,  0.01827234],
        [ 0.01959816,  0.39269803],
        [-0.2730689 , -0.34866914]]])

In [122]:
prices = np.array([
32.7,
25.18,
23.67,
31.48,
36.20
])
returns = prices.reshape((5,1))
returns

array([[32.7 ],
       [25.18],
       [23.67],
       [31.48],
       [36.2 ]])

In [123]:
400 / 55.88

7.158196134574087

In [124]:
prices= np.array([[[32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[28.2, 52.00],
                        [26.4, 47.84],
                        [25.8, 51.67],
                        [32.1, 54.25],
                        [36.6, 55.88]]])

inflows = np.array([0,1000,1000,1000,1000])
weights = np.array([0.6,0.4])

shares = np.zeros((len(inflows),2,2))

for t in range (len(inflows)):
    shares[t] = (inflows[t]*weights) / prices[:,t]

shares.sum(0)
    


array([[86.3736379 , 27.81133275],
       [81.06811809, 30.63410807]])

In [125]:
from dataclasses import dataclass


@dataclass
class Spike:
    rank: int = 1

Spike(3).rank



3

In [126]:
@dataclass
class Transaction:
    delta_shares: np.array
    outflows: int = 0

assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
shares_owned = np.array([[285, 107],[292, 109]])
inflow = 0
goal = (13000,0.8)

cashflow = inflow - goal[0]
current_value = np.sum(shares_owned * prices, 1) 
      
delta_shares = np.where(np.abs(cashflow) <= current_value, np.fix((cashflow*assets_weights) / prices), -shares_owned)
outflows = np.abs(np.sum(delta_shares * prices,axis=1))

print(shares_owned)

max_outflow_value = current_value * goal[1]
np.fix(shares_owned * goal[1])



[[285 107]
 [292 109]]


array([[228.,  85.],
       [233.,  87.]])

In [127]:
goal = (14000,1)
assets_weights = np.array([0.6,0.4])
prices = np.array([[34.2, 59.57],[31.42, 55.88]])
#shares_owned = np.array([[282, 99],[290, 91]])
shares_owned = np.array([[0, 0],[0, 0]])
inflow = 10000

In [128]:
goal_target = goal[0] 
goal_max_outflow_percent = goal[1]
current_assets_value = shares_owned * prices
current_value = np.sum(current_assets_value, 1) 
expected_value = current_value + inflow - goal_target
#max_outflow_value = current_value * goal_max_outflow_percent
    
delta_value = expected_value.reshape((2,1)) * assets_weights - current_assets_value
    
#delta_shares = - np.fix(delta_value / prices)
delta_shares = - delta_value / prices

#outflows = np.round(np.abs(np.sum(delta_shares * prices,axis=1)),2)

#print(outflows)    
#Transaction(delta_shares, outflows)
print(expected_value)
print(assets_weights)
delta_shares



[-4000. -4000.]
[0.6 0.4]


array([[70.1754386 , 26.85915729],
       [76.38446849, 28.63278454]])

In [129]:
shares_owned = np.array([[25,15],[24,17]])
delta = np.array([[5,5],[4,7]])
shares_owned += delta
np.sum(shares_owned * prices[:,1],1)

array([2904.7 , 3009.08])

In [130]:
class PorfoliosSumulator:
    def __init__(self) -> None:
        pass

assets_weights = np.array([0.4,0.6])
shares = np.zeros((scenario_count,t,assets_weights.shape[0]))
initial_wealth =100

#shares[0] = 

initial_wealth *assets_weights


array([40., 60.])

Portfolio class:
- [ ] get withrowals for
    - no goal
    - single goal
    - multiple goals in different times    
    - dla emerytury - coroczne dla kilku celow
- add infusions
- rebalance
- include costs



In [131]:
import tensorflow as tf

In [132]:
weights = tf.Variable([0.3,0.4,0.3])
returns = tf.constant([0.035, 0.085, 0.06])

def loss(weights, returns):
    return tf.tensordot(weights,returns,axes=1)

y = loss(weights, returns)

with tf.GradientTape() as type:
    y = loss(weights, returns)

weights.assign([0.5,0.3,0.2])

type.gradient(y, [weights, returns])



[<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.035, 0.085, 0.06 ], dtype=float32)>,
 None]

In [133]:
arr = np.array([[[30.00, 50.00],       
                        [32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[30.0,	50.0],
                         [28.2,	52.00],
                         [24.82, 47.84],
                         [24.07, 51.67],
                         [25.76, 54.25],
                         [31.42, 55.88]]])
arr.shape

(2, 6, 2)

In [154]:
means = [0.03, 0.05, 0.06, 0.09]
cov = [[0.02, -0.00, -0.00, -0.00],[0.00, 0.04, 0.03, 0.04],[-0.00, 0.03, 0.20, -0.00], [-0.00,0.04, -0.00, 0.13]]      

number_of_scenarios = 600
T = 121
prices = []         

for i in range (number_of_scenarios):
    returns = multivariate_normal.rvs(means,cov, T) + 1
    prices.append(np.cumprod(returns,axis=0)*100)
    #prices.append(returns)

prices = np.absolute(prices)
np.round(prices,2)

prices.shape
            

(600, 121, 4)

In [155]:
from sb_gbi.portfolio_simulator_tf_numpy import PortfoliosSimulator
%reload_ext autoreload
%autoreload 2

inflows = tf.fill(T, 1000.0)
#inflows[0] = 10000.0
prices = tf.constant(np.round(prices,2), dtype=tf.float32)

#assets_weights = np.full((T,4),[0.25,0.25, 0.25, 0.25])
assets_weights = tf.Variable(tf.fill((T,4),0.25))

goals = {
        120: (240000.0,1.0)
    }  


portfolios_simulator = PortfoliosSimulator()



In [159]:
portfolios_simulator.set_params(
        assets_prices=prices,        
        assets_weights= assets_weights,       
        inflows = inflows,
        goals = goals
        )

for i in range(50):
        portfolios_simulator.set_params(
        assets_prices=prices,        
        assets_weights= assets_weights,       
        inflows = inflows,
        goals = goals
        )
        outflows = portfolios_simulator.run()

portfolios_simulator.get_outflows()

[<tf.Tensor 'truediv_240:0' shape=(600,) dtype=float64>]

In [157]:
outflows

In [160]:
with tf.GradientTape() as tape:
    tape.watch(assets_weights)
    portfolios_simulator.run()
    probs = portfolios_simulator.get_goals_achevement_probabilities()

print(tape.gradient(probs, assets_weights))

TypeError: <tf.Tensor 'truediv_240:0' shape=(600,) dtype=float64> is out of scope and cannot be used here. Use return values, explicit Python locals or TensorFlow collections to access it.
Please see https://www.tensorflow.org/guide/function#all_outputs_of_a_tffunction_must_be_return_values for more information.

<tf.Tensor 'truediv_240:0' shape=(600,) dtype=float64> was defined here:
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
      self.io_loop.start()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
      await self.process_one()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
      await dispatch(*args)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\kernelbase.py", line 367, in dispatch_shell
      await result
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\kernelbase.py", line 662, in execute_request
      reply_content = await reply_content
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in run_cell
      result = self._run_cell(
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\IPython\core\interactiveshell.py", line 2935, in _run_cell
      return runner(coro)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\IPython\core\interactiveshell.py", line 3134, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\IPython\core\interactiveshell.py", line 3337, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\matsz\AppData\Local\Temp\ipykernel_41772\3645487140.py", line 15, in <cell line: 8>
      outflows = portfolios_simulator.run()
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 894, in __call__
      result = self._call(*args, **kwds)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 942, in _call
      self._initialize(args, kwds, add_initializers_to=initializers)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 763, in _initialize
      self._variable_creation_fn    # pylint: disable=protected-access
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compiler.py", line 171, in _get_concrete_function_internal_garbage_collected
      concrete_function, _ = self._maybe_define_concrete_function(args, kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compiler.py", line 166, in _maybe_define_concrete_function
      return self._maybe_define_function(args, kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compiler.py", line 396, in _maybe_define_function
      concrete_function = self._create_concrete_function(
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compiler.py", line 300, in _create_concrete_function
      func_graph_module.func_graph_from_py_func(
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1214, in func_graph_from_py_func
      func_outputs = python_func(*func_args, **func_kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 667, in wrapped_fn
      out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compiler.py", line 484, in bound_method_wrapper
      return wrapped_fn(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1189, in autograph_handler
      return autograph.converted_call(
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 331, in converted_call
      return _call_unconverted(f, args, kwargs, options, False)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 455, in _call_unconverted
      return f.__self__.call(args, kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compiler.py", line 447, in call
      return wrapped_fn(self.weakrefself_target__(), *args, **kwargs)
    File "c:\Users\matsz\programowanie\Optymalizacja portfela\sb_gbi\portfolio_simulator_tf_numpy.py", line 109, in run
      delta_shares, outflows = transactions(self.__inflows[t], self.__shares, self.__assets_weights[t],self.__prices[:,t], self.__goals.get(t))
    File "c:\Users\matsz\programowanie\Optymalizacja portfela\sb_gbi\portfolio_simulator_tf_numpy.py", line 54, in transactions
      outflows = np.round(np.where(goal_allocation >= goal_target, goal_target, goal_allocation),2)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\numpy_ops\__init__.py", line 196, in round
      return around(a, decimals=decimals)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\numpy_ops\np_array_ops.py", line 737, in around
      a = math_ops.divide(a, factor)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\util\dispatch.py", line 1176, in op_dispatch_handler
      return dispatch_target(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\math_ops.py", line 478, in divide
      return x / y
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1459, in binary_op_wrapper
      return func(x, y, name=name)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\util\dispatch.py", line 1176, in op_dispatch_handler
      return dispatch_target(*args, **kwargs)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1642, in truediv
      return _truediv_python3(x, y, name)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1580, in _truediv_python3
      return gen_math_ops.real_div(x, y, name=name)
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 8730, in real_div
      _, _, _op, _outputs = _op_def_library._apply_op_helper(
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 795, in _apply_op_helper
      op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\framework\func_graph.py", line 707, in _create_op_internal
      return super()._create_op_internal(  # pylint: disable=protected-access
    File "c:\Users\matsz\miniconda3\envs\portfolio-optimisation\lib\site-packages\tensorflow\python\framework\ops.py", line 3814, in _create_op_internal
      ret = Operation(

The tensor <tf.Tensor 'truediv_240:0' shape=(600,) dtype=float64> cannot be accessed from here, because it was defined in FuncGraph(name=run, id=1263724338960), which is out of scope.

In [ ]:
prices = np.array([[[30.00, 50.00],       
                        [32.7, 51.5],
                        [25.18, 56.14],
                        [23.67, 56.70],
                        [30.53, 57.83],
                        [34.2, 59.57]],
                        [[30.0,	50.0],
                         [28.2,	52.00],
                         [24.82, 47.84],
                         [24.07, 51.67],
                         [25.76, 54.25],
                         [31.42, 55.88]]])

shares = [[10,4],[0,0]]

np.sum(shares * prices[:,-1])

580.28

In [ ]:
def calculate_prob_of_goal_achivement(goals_targets: np.ndarray, goals_outflows: np.ndarray):
    number_of_scenarios = goals_outflows.shape[1]
    total_goals_outflows = np.sum(goals_outflows, axis=1)
    probabilities = total_goals_outflows / np.multiply(goals_targets, number_of_scenarios)
    return probabilities

goal_outflows0 = np.asarray([[0,0],[0,0]])
goal_outflows1 = np.array([[8000, 8000, 8000], [6000, 5775.12, 6000], [6000,6000,6000], [0,0,0]])
goal_target = [8000,6000, 12000, 4000]

calculate_prob_of_goal_achivement(goal_target, goal_outflows1)

calculate_prob_of_goal_achivement([8000,6000], np.array([[8000, 8000], [6000, 5775.12]]))

array([1.     , 0.98126])

In [ ]:
goals = {3: (8000,1), 5: (6000,1)}

list(map(lambda x: x[0],  list(goals.values())))

[8000, 6000]

In [44]:
arr = [11,13,16,20]
v = 12
def find_nearest_values(array, value):
    sub = np.subtract(arr,v)
    i = np.argmin(np.abs(sub))
    return [arr[i],arr[i+1]] if arr[i] < v else [arr[i-1],arr[i]]

find_nearest_values(arr,v)


[11, 13]

In [45]:
np.interp(v,arr,[200,300,350,400])

250.0

In [42]:
#interpolate goal value
goal = (1006, 500)
c1= 1003
c2 = 1003

v1 = 300
v2 = 350

v3 = v1 + (v2-v1)*((goal[0]-c1)/(c2-c1)) + goal[1]

v3


ZeroDivisionError: division by zero

trainable_variables: assets_weights, max_goal_withroval

non_trainable_variables: prices, inflows, goals_target, goals_utilities

output: utilitiy_function (probs * goal_utilities)

secondary_outputs: portfolio irr, portfolio_final_value 

requiremnts:
porfolios_simulator() -> probs


