In [6]:
import sys
#sys.path.append('model')

from model.grid import generateGrid
from model.propabilities import calculateTransitionPropabilitiesForAllPorfolios
from model.investment_planner import get_portfolios_strategies, get_optimal_strategies_for_T
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
portfolios = np.array([[0.0526, 0.037 ],
       [0.0552, 0.0396],
       [0.0577, 0.0463],
       [0.0603, 0.0556],
       [0.0629, 0.0664],
       [0.0655, 0.0781],
       [0.068 , 0.0904],
       [0.0706, 0.1031],
       [0.0732, 0.1159],
       [0.0757, 0.129 ],
       [0.0783, 0.1421],
       [0.0809, 0.1554],
       [0.0834, 0.1687],
       [0.086 , 0.1821],
       [0.0886, 0.1955]])

In [12]:
W0 = 30
iMax = 200
infusions = [5,5,5,5,5]
infusions = [0,0,0,0,0]
goals = [None,None,[20,50],None,[50,100]]
goal_max_costs = [0,0,20,0,50]
#infusions = [ 0]
#goals = [20]


In [18]:
grid = generateGrid(W0,iMax,infusions,goal_max_costs,portfolios[0,0],portfolios[0,1],portfolios[-1,0],portfolios[-1,1])
propabilities = calculateTransitionPropabilitiesForAllPorfolios(portfolios,grid[0],grid[1],infusions[0],1)
Vlast = np.zeros(iMax)
result = get_optimal_strategies_for_T(goals[4],W0,propabilities,Vlast)

port_str = result.porfolios_strategies




IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
W0 = [4, 9, 95,98,100,103,105]
propabilities = np.round(calculateTransitionPropabilitiesForAllPorfolios([portfolios[0],portfolios[2]],W0,W0,5),2)
portfolios_strategies, VTK0, chosen_propabilieties = get_portfolios_strategies(np.array([60,65,70,80,85,90,90]),propabilities)
portfolios_strategies

array([0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [ ]:
W0 = np.array([25,30,60,80])
wtc = W0 - 35
wtc

array([-10,  -5,  25,  45])

In [ ]:
x = [30,60]
y = [44.9, 87.8]
np.interp(45, x, y)

66.35

In [ ]:
np.abs(np.subtract([30,60],45))


array([15, 15])

In [ ]:
np.argmin([2,3,1])

2

In [ ]:
x = [30,60]
y = [0.45, 0.6]
np.interp(45, x, y)

0.525

In [ ]:
probs =  np.array([[[1.,    0.,    0.,    0.   ],
                                [0.926, 0.065, 0.008, 0.   ],
                                [0.017, 0.105, 0.244, 0.634],
                                [0.001, 0.017, 0.075, 0.908]],

                                [[0.65, 0.226, 0.108, 0.016],
                                [0.388, 0.284, 0.222, 0.106],
                                [0.177, 0.234, 0.268, 0.322],
                                [0.14, 0.211, 0.262, 0.387]],

                                [[0.368, 0.275, 0.225, 0.133],
                                [0.287, 0.264, 0.247, 0.202],
                                [0.227, 0.246, 0.256, 0.271],
                                [0.215, 0.241, 0.257, 0.288]]])
VT1 = np.array([0,0,100,100])

print(probs * VT1)

get_portfolios_strategies(VT1,probs)

[[[ 0.   0.   0.   0. ]
  [ 0.   0.   0.8  0. ]
  [ 0.   0.  24.4 63.4]
  [ 0.   0.   7.5 90.8]]

 [[ 0.   0.  10.8  1.6]
  [ 0.   0.  22.2 10.6]
  [ 0.   0.  26.8 32.2]
  [ 0.   0.  26.2 38.7]]

 [[ 0.   0.  22.5 13.3]
  [ 0.   0.  24.7 20.2]
  [ 0.   0.  25.6 27.1]
  [ 0.   0.  25.7 28.8]]]


(array([2, 2, 0, 0], dtype=int64),
 array([35.8, 44.9, 87.8, 98.3]),
 array([[0.368, 0.275, 0.225, 0.133],
        [0.287, 0.264, 0.247, 0.202],
        [0.017, 0.105, 0.244, 0.634],
        [0.001, 0.017, 0.075, 0.908]]))

In [ ]:
arr1 = [1,2,2,4]
arr2 = [4,3,2,1]
np.argmin([arr1,arr2],0)

array([0, 0, 0, 1], dtype=int64)