In [1]:
import Pkg
Pkg.activate("../../../FinancialPlanner")

  Activating project at `c:\Users\matsz\programowanie\Optymalizacja_portfela\FinancialPlanner`


In [2]:
using Revise
using LinearAlgebra
using Distributions
using Random
using StatsPlots
using PDMats
using StatsBase
using Base.Iterators
using DataFrames, TimeSeries, XLSX
using PrettyTables

include("../VARs/utils.jl")
includet("../bootstrap_model.jl")

In [30]:
df = DataFrame(XLSX.readtable("../../data/usa_data.xlsx", "Data", infer_eltypes=true))
data_source = collapse(TimeArray(df; timestamp = :Date), Dates.year, last)

freq = 1
returns = percentchange(data_source[:Total_Stock, :Price_10Y], :log) .* 100
cpi = percentchange(data_source[:CPI], :log) .* 100
real_returns = returns .- cpi
start = Date(1985, 01,01)
end_d = Date(2015, 12, 31)


display("Returns")
display(returns_summarystats(to(from(returns, start),end_d), freq))
display("Real_returns")
display(returns_summarystats(to(from(real_returns, start),end_d), freq))


display("Correlations")
display(cor(values(to(from(real_returns, start),end_d)))) 

"Returns"

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock,17.0547,31.7666,10.3736,24.4081,-46.0709,-1.3837,3.3272,0.0453,2.2904,0.6083,13.9908
Price_10Y,9.4288,26.0455,7.4933,14.6334,-10.627,-0.1471,1.6545,-0.29,-0.6446,0.7947,7.4237


nothing

"Real_returns"

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock_CPI,16.9205,29.0753,7.764,21.6617,-46.1007,-1.2563,0.3809,0.0425,1.7408,0.4589,12.3722
Price_10Y_CPI,9.4787,22.2329,4.8836,11.8448,-13.2188,-0.1283,-0.5841,-0.3468,-0.7481,0.5152,4.1243


nothing

"Correlations"

2×2 Matrix{Float64}:
  1.0      -0.11252
 -0.11252   1.0

In [40]:
assets_names = [:Total_Stock_CPI, :Price_10Y_CPI]
data = to(from(real_returns[assets_names], start),end_d) 

assets_names = [:Total_Stock_CPI, :Price_10Y_CPI]
data = to(from(real_returns[assets_names], start),end_d) 

ret_mean = mean(values(data), dims=1)[1,:]
ret_cov = cov(values(data), dims=1)

T = 25 * freq
n_samples = 10_000
n_assets = length(assets_names)

scenarios = zeros(n_assets, T, n_samples)

for t in 1:T 
    scenarios[:,t, :] = rand(MvNormal(ret_mean, ret_cov), n_samples)
end

periods = [1,5, 10, 25]
ret_in_years = cum_returns_in_periods(scenarios, periods, freq, true)
print_scenarios_summary(ret_in_years, assets_names, string.(periods))
n_assets = length(assets_names)
for a in 1:n_assets
    print_scenarios_percentiles(ret_in_years[a, :, :], [.05, .25, .5, .75, .95], string.(periods), string.(assets_names[a]))
end  


,Total_Stock_CPI,Price_10Y_CPI
1,0.083,0.0325
5,0.0818,0.032
10,0.082,0.0319
25,0.0816,0.0319


,Total_Stock_CPI,Price_10Y_CPI
1,0.1629,0.099
5,0.0736,0.0444
10,0.053,0.0315
25,0.0332,0.0198


,Total_Stock_CPI,Price_10Y_CPI
1,-0.006,-0.028
5,0.0134,-0.0131
10,-0.0021,0.0139
25,0.0138,0.019


,Total_Stock_CPI,Price_10Y_CPI
1,0.0515,0.015
5,-0.0109,0.0064
10,-0.0391,-0.0946
25,0.0527,-0.09


,0.05,0.25,0.5,0.75,0.95
1,-0.1837,-0.0258,0.0819,0.1941,0.3484
5,-0.0379,0.0313,0.0814,0.1312,0.2028
10,-0.0044,0.0459,0.0819,0.1186,0.1689
25,0.0275,0.0591,0.0814,0.1041,0.1365


,0.05,0.25,0.5,0.75,0.95
1,-0.132,-0.0343,0.0331,0.0993,0.1942
5,-0.0408,0.0025,0.032,0.062,0.1041
10,-0.0201,0.0103,0.0319,0.0534,0.0836
25,-0.0006,0.0182,0.032,0.0451,0.0645


In [32]:
mdd, mddl = max_drawdown_and_length(scenarios[1,:,:])

display(assets_names[1])
display("mdd")
display(quantile(mdd, [.03, .25, .5, .75, .97])')
display("mddl")
display(quantile(mddl, [.03, .25, .5, .75, .97])')

mdd, mddl = max_drawdown_and_length(scenarios[2,:,:])

display(assets_names[2])
display("mdd")
display(quantile(mdd, [.03, .25, .5, .75, .97])')
display("mddl")
display(quantile(mddl, [.03, .25, .5, .75, .97])')

:Total_Stock_CPI

"mdd"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.999995  1.0  1.0  1.0  1.0

"mddl"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 3.0  4.0  6.0  9.0  17.0

:Price_10Y_CPI

"mdd"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.998119  0.999997  1.0  1.0  1.0

"mddl"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 2.0  4.0  6.0  8.0  15.0

### MVNormal based on calibration

In [42]:
df = DataFrame(XLSX.readtable("../../data/usa_data.xlsx", "Data", infer_eltypes=true))
data_source = collapse(TimeArray(df; timestamp = :Date), Dates.year, last)

freq = 1
returns = percentchange(data_source[:Total_Stock, :Price_10Y], :log)
cpi = percentchange(data_source[:CPI], :log)
real_returns = returns .- cpi
start = Date(1985, 01,01)
end_d = Date(2024, 12, 31)


display("Returns")
display(returns_summarystats(to(from(returns, start),end_d), freq))
display("Real_returns")
display(returns_summarystats(to(from(real_returns, start),end_d), freq))


display("Correlations")
display(cor(values(to(from(real_returns, start),end_d)))) 

"Returns"

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock,0.1655,0.3177,0.109,0.2407,-0.4607,-1.3705,0.0402,-0.0527,2.0965,0.6585,0.1461
Price_10Y,0.0953,0.2605,0.0592,0.1252,-0.1786,-0.1749,0.0025,-0.1121,-0.1603,0.6207,0.0597


nothing

"Real_returns"

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock_CPI,0.1654,0.2908,0.0817,0.2045,-0.461,-1.2908,0.0059,-0.0458,1.6171,0.494,0.1265
Price_10Y_CPI,0.0995,0.2223,0.0319,0.1043,-0.2408,-0.3399,-0.0138,-0.1103,0.095,0.3204,0.0202


nothing

"Correlations"

2×2 Matrix{Float64}:
 1.0        0.0479353
 0.0479353  1.0

In [34]:
#.095 * .1 + .095

0.1043 * .6 + 1. * 0.4

0.46258

In [41]:
means = [.055, .01]
stds = [.175, .10]
corrm = [1. 0.048; .048 1.]

covm = cor2cov(corrm, stds)


T = 25 * freq
n_samples = 10_000
n_assets = length(assets_names)

scenarios = zeros(n_assets, T, n_samples)

for t in 1:T 
    scenarios[:,t, :] = rand(MvNormal(means, covm), n_samples)
end

periods = [1,5, 10, 25]
ret_in_years = cum_returns_in_periods(scenarios, periods, freq, true)
print_scenarios_summary(expm1.(ret_in_years), assets_names, string.(periods))
n_assets = length(assets_names)
for a in 1:n_assets
    print_scenarios_percentiles(expm1.(ret_in_years[a, :, :]), [.05, .25, .5, .75, .95], string.(periods), string.(assets_names[a]))
end  





,Total_Stock_CPI,Price_10Y_CPI
1,0.0705,0.0151
5,0.06,0.0109
10,0.0581,0.0103
25,0.0569,0.0101


,Total_Stock_CPI,Price_10Y_CPI
1,0.1897,0.102
5,0.0826,0.0456
10,0.0584,0.0321
25,0.0367,0.0203


,Total_Stock_CPI,Price_10Y_CPI
1,0.562,0.3432
5,0.2495,0.0955
10,0.1471,0.0689
25,0.1251,0.0607


,Total_Stock_CPI,Price_10Y_CPI
1,0.5548,0.2187
5,0.0976,0.0367
10,0.0265,-0.0017
25,0.0804,-0.0558


,0.05,0.25,0.5,0.75,0.95
1,-0.2141,-0.0623,0.0538,0.1834,0.4107
5,-0.0698,0.0015,0.0568,0.1145,0.1995
10,-0.0356,0.0176,0.0566,0.097,0.1557
25,-0.0025,0.0315,0.0564,0.0813,0.1179


,0.05,0.25,0.5,0.75,0.95
1,-0.1429,-0.0556,0.0086,0.0798,0.192
5,-0.0628,-0.0197,0.0101,0.0417,0.0862
10,-0.0417,-0.0116,0.0101,0.0316,0.0639
25,-0.0228,-0.0039,0.0101,0.0235,0.0437


In [36]:
mdd, mddl = max_drawdown_and_length(scenarios[1,:,:])

display(assets_names[1])
display("mdd")
display(quantile(mdd, [.03, .25, .5, .75, .97])')
display("mddl")
display(quantile(mddl, [.03, .25, .5, .75, .97])')

mdd, mddl = max_drawdown_and_length(scenarios[2,:,:])

display(assets_names[2])
display("mdd")
display(quantile(mdd, [.03, .25, .5, .75, .97])')
display("mddl")
display(quantile(mddl, [.03, .25, .5, .75, .97])')

:Total_Stock_CPI

"mdd"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.156953  0.272729  0.355688  0.458981  0.665005

"mddl"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 3.0  6.0  8.0  12.0  22.0

:Price_10Y_CPI

"mdd"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.129226  0.226687  0.307621  0.406238  0.600882

"mddl"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 4.0  8.0  12.0  18.0  25.0

In [37]:
moving_stds = moving(std, real_returns, 20) 

display(mean(moving_stds))

display("bonds standard devations")
display(quantile(values(moving_stds)[:,1], [.03, .25, .5, .75, .97])')


display("equity standard devations")
display(quantile(values(moving_stds)[:,2], [.03, .25, .5, .75, .97])')



1×2 TimeArray{Float64, 2, Date, Matrix{Float64}} 2024-07-01 to 2024-07-01
┌────────────┬─────────────────┬───────────────┐
│            │ Total_Stock_CPI │ Price_10Y_CPI │
├────────────┼─────────────────┼───────────────┤
│ 2024-07-01 │        0.169599 │     0.0933804 │
└────────────┴─────────────────┴───────────────┘

"bonds standard devations"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.120654  0.159893  0.175245  0.183315  0.19649

"equity standard devations"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.0587443  0.0805222  0.0947667  0.11453  0.122471

MVnormal based on equity corrected growth

In [51]:
data_source = collapse(TimeArray(df; timestamp = :Date), Dates.year, last)

freq = 1
returns = percentchange(data_source[:Total_Stock, :Price_10Y], :log)
cpi = percentchange(data_source[:CPI], :log)
Δcape = percentchange(data_source[:CAPE], :log)
corrected_eq_returns = returns[:Total_Stock] .- Δcape
returns = merge(returns, corrected_eq_returns)
real_returns = returns .- cpi
real_corrected_eq_returns = corrected_eq_returns .- cpi
real_returns = merge(real_returns, real_corrected_eq_returns)
start = Date(1985, 01,01)
end_d = Date(2024, 12, 31)


display("Returns")
display(returns_summarystats(to(from(returns, start),end_d), freq))
display("Real_returns")
display(returns_summarystats(to(from(real_returns, start),end_d), freq))


display("Correlations")
display(cor(values(to(from(real_returns, start),end_d)))) 

"Returns"

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock,0.1655,0.3177,0.109,0.2407,-0.4607,-1.3705,0.0402,-0.0527,2.0965,0.6585,0.1461
Price_10Y,0.0953,0.2605,0.0592,0.1252,-0.1786,-0.1749,0.0025,-0.1121,-0.1603,0.6207,0.0597
Total_Stock_CAPE,0.0603,0.1848,0.0776,0.1151,-0.0717,-0.431,0.0452,-0.0236,0.1973,1.2865,0.0704


nothing

"Real_returns"

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock_CPI,0.1654,0.2908,0.0817,0.2045,-0.461,-1.2908,0.0059,-0.0458,1.6171,0.494,0.1265
Price_10Y_CPI,0.0995,0.2223,0.0319,0.1043,-0.2408,-0.3399,-0.0138,-0.1103,0.095,0.3204,0.0202
Total_Stock_CAPE_CPI,0.0575,0.1602,0.0503,0.0918,-0.0908,-0.4718,0.0121,0.0049,0.082,0.8757,0.0462
Total_Stock_CAPE_CPI_1,0.0575,0.1602,0.0503,0.0918,-0.0908,-0.4718,0.0121,0.0049,0.082,0.8757,0.0462


nothing

"Correlations"

4×4 Matrix{Float64}:
 1.0         0.0479353   0.239536    0.239536
 0.0479353   1.0        -0.0203359  -0.0203359
 0.239536   -0.0203359   1.0         1.0
 0.239536   -0.0203359   1.0         1.0

In [66]:
ret = values(returns[:Total_Stock])
std(ret; mean=0.08)


0.165066455931727