In [1]:
import Pkg
Pkg.activate("../../../FinancialPlanner")

  Activating project at `c:\Users\matsz\programowanie\Optymalizacja_portfela\FinancialPlanner`


In [2]:
using Revise
using LinearAlgebra
using Distributions
using Random
using StatsPlots
using PDMats
using StatsBase
using Base.Iterators
using DataFrames, TimeSeries, XLSX
using PrettyTables

In [3]:
includet("../VARs/utils.jl")
includet("../VARs/VAR_OLS.jl")

In [4]:
df = DataFrame(XLSX.readtable("../../data/usa_data.xlsx", "Data", infer_eltypes=true))
data_source = collapse(TimeArray(df; timestamp = :Date), Dates.quarter, last)

freq = 4
#:Price_10Y
returns = percentchange(data_source[:Total_Stock], :log)
cpi = percentchange(data_source[:CPI], :log) 

real_t_bill = log1p.(data_source[:T_Bill])./freq .- cpi

excess_returns = returns .- log1p.(data_source[:T_Bill]./freq)

dy = log.(data_source[:Dividend]) .- log.(data_source[:Stock_Price])

term = data_source[:Yeld_10Y] ./freq .- data_source[:T_Bill] ./freq

#data = merge(excess_returns, real_t_bill, dy, term, log1p.(data_source[:T_Bill]))
data = merge(excess_returns, real_t_bill, dy, term, cpi)

start = Date(1975, 01,01)
end_d = Date(2020, 12, 31)
s_data = to(from(data, start),end_d)

display(returns_summarystats(s_data, freq)) 
display(cor(values(s_data)))

,std,max,mean,p75th,min,skewness,p25th,autocor,kurtosis,sr,median
Total_Stock_T_Bill,0.1618,0.7699,0.0713,0.259,-1.0747,-0.7743,-0.0787,0.0036,1.1287,0.4407,0.1145
T_Bill_CPI,0.0166,0.1019,0.0074,0.0291,-0.0832,0.0704,-0.0152,0.3505,0.2942,0.4474,0.0095
Dividend_Stock_Price,0.863,-11.1063,-14.6688,-13.3062,-17.9779,0.2422,-15.943,0.9739,-0.9751,-16.9973,-15.2277
Yeld_10Y_T_Bill,0.0062,0.0397,0.0172,0.0264,-0.0306,-0.7037,0.0084,0.769,0.7198,2.7644,0.019
CPI,0.018,0.1612,0.0351,0.0496,-0.1016,0.3024,0.0159,0.4101,2.0781,1.9539,0.0326


nothing

5×5 Matrix{Float64}:
  1.0         -0.088044   -0.0947785   0.0552798   0.00800211
 -0.088044     1.0         0.183927   -0.0795142  -0.530145
 -0.0947785    0.183927    1.0         0.0762043   0.465928
  0.0552798   -0.0795142   0.0762043   1.0        -0.258195
  0.00800211  -0.530145    0.465928   -0.258195    1.0

In [9]:
assets_names = colnames(s_data)
T, n_assets = size(s_data)
model = VARModel(s_data)
model_summary(model)

,const,Total_Stock_T_Bill,T_Bill_CPI,Dividend_Stock_Price,Yeld_10Y_T_Bill,CPI,std
Total_Stock_T_Bill,0.289,0.019,-2.9824,0.0601,-3.6999,-3.4854,0.079
T_Bill_CPI,-0.0354,-0.0001,0.8692,-0.0071,0.7639,0.741,0.007
Dividend_Stock_Price,-0.2314,-0.0002,1.7257,0.9487,2.751,2.5839,0.0815
Yeld_10Y_T_Bill,0.0016,-0.003,-0.0009,0.0002,0.7731,-0.0014,0.002
CPI,0.0377,0.0049,0.0813,0.0077,-0.6711,0.2179,0.0075


,Total_Stock_T_Bill,T_Bill_CPI,Dividend_Stock_Price,Yeld_10Y_T_Bill,CPI
Total_Stock_T_Bill,1.0,-0.0,-0.98,0.07,-0.02
T_Bill_CPI,-0.0,1.0,-0.02,-0.12,-0.95
Dividend_Stock_Price,-0.98,-0.02,1.0,-0.07,0.03
Yeld_10Y_T_Bill,0.07,-0.12,-0.07,1.0,-0.12
CPI,-0.02,-0.95,0.03,-0.12,1.0


In [17]:
model.C


6×5 Matrix{Float64}:
  0.289049   -0.0354476    -0.231418      0.00157373    0.0377067
  0.0190035  -0.000100197  -0.000184073  -0.00299387    0.0049271
 -2.98237     0.8692        1.72573      -0.000892236   0.081301
  0.060111   -0.00706089    0.948739      0.000150678   0.00770491
 -3.69992     0.763949      2.75098       0.773074     -0.671072
 -3.48542     0.740991      2.58391      -0.00144379    0.217913

In [20]:
inv(Matrix(I(5)) - model.C[2:end,:]) * model.C[1,:]

5-element Vector{Float64}:
   -1.4353330281807046
 -545.0480067707675
  -17.26785096462086
 -345.93605021470603
 -566.3747569971226

In [6]:
scenarios = simulate(model, 25*freq, 10_000)
periods = [1,5, 15, 25]
ret_in_years = cum_returns_in_periods(scenarios, periods, freq, true)
print_scenarios_summary(ret_in_years, assets_names, string.(periods))

for a in 1:n_assets
    print_scenarios_percentiles(ret_in_years[a, :, :], [.05, .25, .5, .75, .95], string.(periods), string.(assets_names[a]))
end  

,Total_Stock_T_Bill,T_Bill_CPI,Dividend_Stock_Price,Yeld_10Y_T_Bill,CPI
1,0.1958,-0.0177,-16.7195,0.0097,0.0195
5,0.1044,-0.0136,-16.8196,0.0136,0.0152
15,0.0835,-0.0119,-16.9091,0.0148,0.013
25,0.0793,-0.0118,-16.9627,0.0151,0.0122


,Total_Stock_T_Bill,T_Bill_CPI,Dividend_Stock_Price,Yeld_10Y_T_Bill,CPI
1,0.1307,0.013,0.2936,0.0062,0.0149
5,0.055,0.0104,0.6411,0.0065,0.0119
15,0.0331,0.0096,0.9044,0.0042,0.0117
25,0.0267,0.0096,1.0231,0.0033,0.0122


,Total_Stock_T_Bill,T_Bill_CPI,Dividend_Stock_Price,Yeld_10Y_T_Bill,CPI
1,-0.04,-0.018,0.0494,-0.0163,0.0407
5,-0.0074,-0.0175,0.0089,-0.0206,-0.0056
15,0.0042,-0.0137,-0.0437,-0.0208,-0.0424
25,0.0134,-0.0065,-0.0689,-0.0116,-0.035


,Total_Stock_T_Bill,T_Bill_CPI,Dividend_Stock_Price,Yeld_10Y_T_Bill,CPI
1,0.0816,0.0685,-0.0111,0.0649,0.0855
5,-0.0242,-0.0397,-0.0471,-0.0399,-0.0353
15,0.0088,0.0213,-0.0177,0.0451,0.0503
25,0.05,0.0599,0.0378,0.0523,0.0844


,0.05,0.25,0.5,0.75,0.95
1,-0.0194,0.1079,0.1958,0.2849,0.4086
5,0.0145,0.0667,0.1044,0.1417,0.1943
15,0.0296,0.0612,0.0837,0.1058,0.138
25,0.0358,0.0614,0.0792,0.0972,0.1233


,0.05,0.25,0.5,0.75,0.95
1,-0.0388,-0.0264,-0.0177,-0.0091,0.0038
5,-0.0307,-0.0206,-0.0137,-0.0066,0.0034
15,-0.0276,-0.0185,-0.0119,-0.0054,0.0035
25,-0.0278,-0.0182,-0.0118,-0.0054,0.0038


,0.05,0.25,0.5,0.75,0.95
1,-17.195,-16.9177,-16.7229,-16.5208,-16.2301
5,-17.8627,-17.2594,-16.8192,-16.3894,-15.7636
15,-18.3982,-17.5209,-16.9043,-16.2879,-15.4381
25,-18.6571,-17.6602,-16.9413,-16.2633,-15.3087


,0.05,0.25,0.5,0.75,0.95
1,-0.0006,0.0057,0.0098,0.014,0.0199
5,0.0029,0.0092,0.0135,0.018,0.0242
15,0.0078,0.012,0.0148,0.0177,0.0217
25,0.0096,0.0129,0.0151,0.0173,0.0206


,0.05,0.25,0.5,0.75,0.95
1,-0.0049,0.0095,0.0195,0.0293,0.0442
5,-0.0044,0.0072,0.0151,0.0233,0.0348
15,-0.0064,0.0052,0.0131,0.021,0.0322
25,-0.008,0.0042,0.0123,0.0205,0.0322


In [7]:
real_equity_scenarios = reshape(scenarios[1, :, :] .+ scenarios[2, :,:], 1, 101, 10_000)
real_bond_scenarios = reshape(scenarios[2, :, :] .+ scenarios[4, :,:], 1, 101, 10_000)

ret_in_years = cum_returns_in_periods(vcat(real_equity_scenarios, real_bond_scenarios), periods, freq, true)
print_scenarios_summary(ret_in_years, assets_names[1:2], string.(periods))

for a in 1:2
    print_scenarios_percentiles(ret_in_years[a, :, :], [.01, 0.025, .05, .25, .5, .75, .95, .975, .99], string.(periods), string.(assets_names[a]))
end  



,Total_Stock_T_Bill,T_Bill_CPI
1,0.1781,-0.008
5,0.0907,-0.0001
15,0.0716,0.0029
25,0.0675,0.0033


,Total_Stock_T_Bill,T_Bill_CPI
1,0.1326,0.0138
5,0.0548,0.011
15,0.028,0.0095
25,0.02,0.0095


,Total_Stock_T_Bill,T_Bill_CPI
1,-0.0389,-0.0113
5,-0.0105,-0.0508
15,0.0066,-0.0118
25,0.0189,-0.0132


,Total_Stock_T_Bill,T_Bill_CPI
1,0.0664,0.0513
5,0.0133,-0.0558
15,-0.0176,0.0469
25,-0.007,0.0257


,0.01,0.025,0.05,0.25,0.5,0.75,0.95,0.975,0.99
1,-0.1336,-0.0839,-0.0405,0.089,0.1777,0.2684,0.3927,0.4402,0.4805
5,-0.0356,-0.016,0.0015,0.0535,0.091,0.1282,0.18,0.1977,0.2186
15,0.0061,0.0163,0.0258,0.0526,0.0716,0.0906,0.1174,0.1266,0.1378
25,0.0212,0.0289,0.0349,0.0539,0.0675,0.0812,0.1008,0.1066,0.113


,0.01,0.025,0.05,0.25,0.5,0.75,0.95,0.975,0.99
1,-0.0402,-0.0352,-0.0308,-0.0171,-0.0079,0.0015,0.0148,0.0189,0.0241
5,-0.0266,-0.022,-0.0184,-0.0076,0.0,0.0074,0.0182,0.0215,0.0248
15,-0.0188,-0.0155,-0.0125,-0.0036,0.003,0.0094,0.0184,0.0217,0.0249
25,-0.0192,-0.0157,-0.0125,-0.0031,0.0032,0.0097,0.0189,0.0218,0.0254


In [8]:
mdd, mddl = max_drawdown_and_length(real_equity_scenarios[1,:,:])

display(assets_names[1])
display("mdd")
display(quantile(mdd, [.03, .25, .5, .75, .97])')
display("mddl")
display(quantile(mddl, [.03, .25, .5, .75, .97])')

mdd, mddl = max_drawdown_and_length(real_bond_scenarios[1,:,:])

display(assets_names[2])
display("mdd")
display(quantile(mdd, [.03, .25, .5, .75, .97])')
display("mddl")
display(quantile(mddl, [.03, .25, .5, .75, .97])')

:Total_Stock_T_Bill

"mdd"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.222021  0.296651  0.349321  0.408901  0.537509

"mddl"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 12.0  18.0  24.0  32.0  55.0

:T_Bill_CPI

"mdd"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 0.027789  0.0633728  0.104199  0.172073  0.343693

"mddl"

1×5 adjoint(::Vector{Float64}) with eltype Float64:
 12.0  29.0  48.0  75.0  101.0