In [7]:
import numpy as np
import pyesg
from regime_switching_brownian_motion import IndependentLogNormal


In [8]:
model = IndependentLogNormal(mu=0.07,sigma=0.21)

In [29]:
scenarios = model.scenarios(100,1,100,30)

259.94592515379014

In [3]:
corr = np.array([[1,0.7], [0.7,1]])
corr

array([[1. , 0.7],
       [0.7, 1. ]])

In [4]:
L = np.linalg.cholesky(corr)
L

array([[1.        , 0.        ],
       [0.7       , 0.71414284]])

In [8]:
sig = [1,2]

In [17]:
c = sig @ L
c

array([2.4       , 1.42828569])

In [32]:
rand = np.random.normal(size=(100000,2))


In [33]:
result = rand * c

In [38]:
np.corrcoef(result.T)

array([[1.        , 0.00341387],
       [0.00341387, 1.        ]])

In [39]:
np.diag([3,6])

array([[3, 0],
       [0, 6]])

In [4]:
model = pyesg.WienerProcess.example()

In [6]:
model.coefs()

{'mu': 0.05, 'sigma': 0.2}

In [15]:
class RegimeS(pyesg.WienerProcess):
    def __init__(self, mu: float, sigma: float) -> None:
        super().__init__(mu, sigma)

    def step(self, x0):
        print('step called')
        return super().step(x0,1)

In [16]:
mod = RegimeS(0.05,0.15)

In [41]:
mod.step(100)

step called


array([100.05832942])