In [1]:
import numpy as np
import pyesg
from regime_switching_brownian_motion import IndependentLogNormal


In [8]:
model = IndependentLogNormal(mu=0.07,sigma=0.21)

In [29]:
scenarios = model.scenarios(100,1,100,30)

In [55]:
np.random.uniform(0,1.01,(2,2,2))

array([[[0.24296514, 0.74530591],
        [0.62731273, 0.7276713 ]],

       [[0.61482723, 0.40386556],
        [0.82297498, 0.30307517]]])

In [3]:
corr = np.array([[1,0.7], [0.7,1]])
corr

array([[1. , 0.7],
       [0.7, 1. ]])

In [4]:
L = np.linalg.cholesky(corr)
L

array([[1.        , 0.        ],
       [0.7       , 0.71414284]])

In [8]:
sig = [1,2]

In [17]:
c = sig @ L
c

array([2.4       , 1.42828569])

In [32]:
rand = np.random.normal(size=(100000,2))


In [33]:
result = rand * c

In [38]:
np.corrcoef(result.T)

array([[1.        , 0.00341387],
       [0.00341387, 1.        ]])

In [39]:
np.diag([3,6])

array([[3, 0],
       [0, 6]])

In [4]:
model = pyesg.WienerProcess.example()

In [6]:
model.coefs()

{'mu': 0.05, 'sigma': 0.2}

In [15]:
class RegimeS(pyesg.WienerProcess):
    def __init__(self, mu: float, sigma: float) -> None:
        super().__init__(mu, sigma)

    def step(self, x0):
        print('step called')
        return super().step(x0,1)

In [16]:
mod = RegimeS(0.05,0.15)

In [41]:
mod.step(100)

step called


array([100.05832942])

In [10]:
n_assets = 2
n_scenarios = 8
H = 3

asset_returns = np.array([[1.25,1.14],
                          [1.06,1.12]])

returns_tree = np.zeros((n_assets,n_scenarios,H))

ret_scen = np.array([[[1,2,3,4],
                     [1,2,5,6],
                     [1,3,5,7]],
                    [[5,6,7,8],
                     [3,4,7,8],
                     [2,4,6,8]]])

for variant in range(len(asset_returns)):
  for a in range(n_assets):
    for t in range(H):
      returns_tree[a,ret_scen[variant,t]-1,t] = asset_returns[variant,a]
      #print(f'var: {variant}, a: {a}, t: {t}')

In [11]:
returns_tree

array([[[1.25, 1.25, 1.25],
        [1.25, 1.25, 1.06],
        [1.25, 1.06, 1.25],
        [1.25, 1.06, 1.06],
        [1.06, 1.25, 1.25],
        [1.06, 1.25, 1.06],
        [1.06, 1.06, 1.25],
        [1.06, 1.06, 1.06]],

       [[1.14, 1.14, 1.14],
        [1.14, 1.14, 1.12],
        [1.14, 1.12, 1.14],
        [1.14, 1.12, 1.12],
        [1.12, 1.14, 1.14],
        [1.12, 1.14, 1.12],
        [1.12, 1.12, 1.14],
        [1.12, 1.12, 1.12]]])

In [18]:
assets = ['stocks', 'bonds']
scenarios = list(range(1,9))
H = list(range(3))

{(asset,scenario,t): returns_tree[a,s,t] 
 for a,asset in enumerate(assets)
 for s,scenario in enumerate(scenarios)
 for t in H
 }

{('stocks', 1, 0): 1.25,
 ('stocks', 1, 1): 1.25,
 ('stocks', 1, 2): 1.25,
 ('stocks', 2, 0): 1.25,
 ('stocks', 2, 1): 1.25,
 ('stocks', 2, 2): 1.06,
 ('stocks', 3, 0): 1.25,
 ('stocks', 3, 1): 1.06,
 ('stocks', 3, 2): 1.25,
 ('stocks', 4, 0): 1.25,
 ('stocks', 4, 1): 1.06,
 ('stocks', 4, 2): 1.06,
 ('stocks', 5, 0): 1.06,
 ('stocks', 5, 1): 1.25,
 ('stocks', 5, 2): 1.25,
 ('stocks', 6, 0): 1.06,
 ('stocks', 6, 1): 1.25,
 ('stocks', 6, 2): 1.06,
 ('stocks', 7, 0): 1.06,
 ('stocks', 7, 1): 1.06,
 ('stocks', 7, 2): 1.25,
 ('stocks', 8, 0): 1.06,
 ('stocks', 8, 1): 1.06,
 ('stocks', 8, 2): 1.06,
 ('bonds', 1, 0): 1.14,
 ('bonds', 1, 1): 1.14,
 ('bonds', 1, 2): 1.14,
 ('bonds', 2, 0): 1.14,
 ('bonds', 2, 1): 1.14,
 ('bonds', 2, 2): 1.12,
 ('bonds', 3, 0): 1.14,
 ('bonds', 3, 1): 1.12,
 ('bonds', 3, 2): 1.14,
 ('bonds', 4, 0): 1.14,
 ('bonds', 4, 1): 1.12,
 ('bonds', 4, 2): 1.12,
 ('bonds', 5, 0): 1.12,
 ('bonds', 5, 1): 1.14,
 ('bonds', 5, 2): 1.14,
 ('bonds', 6, 0): 1.12,
 ('bonds', 6, 1)

In [6]:
returns_tree = np.zeros((n_assets,n_scenarios,H))

returns_tree[1,ret_scen[0,1]-1,1]  = asset_returns[0,1]

returns_tree

array([[[0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ]],

       [[0.  , 1.14, 0.  ],
        [0.  , 1.14, 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 1.14, 0.  ],
        [0.  , 1.14, 0.  ],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ]]])